// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/about/bk" | "/admin" | "/admin-login" | "/admin/analytics" | "/admin/backup" | "/admin/backup/pages" | "/admin/collections" | "/admin/invite/[token]" | "/admin/invites" | "/admin/pages" | "/admin/pages/bk" | "/admin/records" | "/admin/settings" | "/admin/settings/bk" | "/admin/signin" | "/admin/sources" | "/admin/users" | "/auth/reset-password" | "/auth/sign-in" | "/community" | "/community/reading-lists/[id]" | "/copyright" | "/curator" | "/curator/media" | "/home" | "/library" | "/my/bookmarks" | "/my/lists" | "/my/searches" | "/my/workbench" | "/my/workbench/collaborators" | "/my/workbench/exports" | "/my/workbench/notes" | "/my/workbench/projects" | "/my/workbench/projects/[id]" | "/my/workbench/reading-lists" | "/my/workbench/saved-records" | "/my/workbench/tasks" | "/privacy" | "/records/[id]" | "/reset-password" | "/signin" | "/signup" | "/sources" | "/takedown" | "/terms" | "/workspace"
type AppRouteHandlerRoutes = "/api/admin-login" | "/api/collections" | "/api/core-search" | "/api/core-search/backup" | "/api/curator/media" | "/api/curator/media-links" | "/api/curator/media/[id]" | "/api/external-open-access" | "/api/reading-lists/[id]/export" | "/api/reading-lists/export-all" | "/api/records" | "/api/search-term" | "/api/settings" | "/api/site-content" | "/api/sources" | "/api/top-searches" | "/api/workbench/export" | "/api/workspace/record-tools" | "/auth/callback" | "/auth/confirm" | "/auth/signout"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/admin/backup" | "/my/workbench"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/about/bk": {}
  "/admin": {}
  "/admin-login": {}
  "/admin/analytics": {}
  "/admin/backup": {}
  "/admin/backup/pages": {}
  "/admin/collections": {}
  "/admin/invite/[token]": { "token": string; }
  "/admin/invites": {}
  "/admin/pages": {}
  "/admin/pages/bk": {}
  "/admin/records": {}
  "/admin/settings": {}
  "/admin/settings/bk": {}
  "/admin/signin": {}
  "/admin/sources": {}
  "/admin/users": {}
  "/api/admin-login": {}
  "/api/collections": {}
  "/api/core-search": {}
  "/api/core-search/backup": {}
  "/api/curator/media": {}
  "/api/curator/media-links": {}
  "/api/curator/media/[id]": { "id": string; }
  "/api/external-open-access": {}
  "/api/reading-lists/[id]/export": { "id": string; }
  "/api/reading-lists/export-all": {}
  "/api/records": {}
  "/api/search-term": {}
  "/api/settings": {}
  "/api/site-content": {}
  "/api/sources": {}
  "/api/top-searches": {}
  "/api/workbench/export": {}
  "/api/workspace/record-tools": {}
  "/auth/callback": {}
  "/auth/confirm": {}
  "/auth/reset-password": {}
  "/auth/sign-in": {}
  "/auth/signout": {}
  "/community": {}
  "/community/reading-lists/[id]": { "id": string; }
  "/copyright": {}
  "/curator": {}
  "/curator/media": {}
  "/home": {}
  "/library": {}
  "/my/bookmarks": {}
  "/my/lists": {}
  "/my/searches": {}
  "/my/workbench": {}
  "/my/workbench/collaborators": {}
  "/my/workbench/exports": {}
  "/my/workbench/notes": {}
  "/my/workbench/projects": {}
  "/my/workbench/projects/[id]": { "id": string; }
  "/my/workbench/reading-lists": {}
  "/my/workbench/saved-records": {}
  "/my/workbench/tasks": {}
  "/privacy": {}
  "/records/[id]": { "id": string; }
  "/reset-password": {}
  "/signin": {}
  "/signup": {}
  "/sources": {}
  "/takedown": {}
  "/terms": {}
  "/workspace": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/backup": never
  "/my/workbench": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
