"use client";
import LineLoader from "@/app/home-next/ui/LineLoader";
import { useEffect,useState } from "react";
import { blankEdition,type Edition } from "@/lib/knowledge/edition";
export default function EditionEditor({id,records}:{id:string;records:Array<{id:string;title:string}>}) {
  const [document,setDocument]=useState<Edition>(blankEdition);const [revision,setRevision]=useState(0);const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{let active=true;fetch(`/api/knowledge/collections/${id}`).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(active){setDocument({...blankEdition(),...data.edition?.document});setRevision(data.edition?.revision??0);setReady(true);}}).catch(()=>{if(active)setMessage("Collection writing could not load. Reload to try again.");});return()=>{active=false;};},[id]);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const r=await fetch(`/api/knowledge/collections/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({document,revision})});const data=await r.json();if(!r.ok)throw Error(data.error);setRevision(data.revision);setDocument(data.document);setMessage("Collection writing saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
  return <details style={{margin:"28px 0",padding:24,border:"1px solid var(--border, #ddd)",borderRadius:20}}><summary>Shape this collection · exhibition, research or teaching</summary><form onSubmit={save} style={{display:"grid",gap:18,marginTop:24}}>
    <p>This writing is shared when you publish the collection. Saved-record notes remain private.</p>
    {([['introduction','Introduction'],['rationale','Why these records belong together'],['prompts','Teaching prompts']] as const).map(([key,label])=><label key={key}>{label}<textarea disabled={!ready} value={document[key]} maxLength={6000} onChange={e=>setDocument({...document,[key]:e.target.value})} rows={3} style={{display:"block",width:"100%",font:"inherit"}}/></label>)}
    <label>Sections · one heading per line<textarea disabled={!ready} value={document.sections.map(s=>s.title).join('\n')} onChange={e=>setDocument({...document,sections:e.target.value.split('\n').slice(0,30).map((title,index)=>({title,recordIds:document.sections[index]?.recordIds??[]}))})} rows={3} style={{display:"block",width:"100%",font:"inherit"}}/></label>
    {records.map(record=><fieldset key={record.id} style={{border:"1px solid #ddd",borderRadius:12,padding:16}}><legend>{record.title}</legend><label>Section <select value={document.sections.findIndex(s=>s.recordIds.includes(record.id))} onChange={e=>{const selected=Number(e.target.value);setDocument({...document,sections:document.sections.map((s,index)=>({...s,recordIds:[...s.recordIds.filter(x=>x!==record.id),...(index===selected?[record.id]:[])]}))});}}><option value={-1}>Unsectioned</option>{document.sections.map((s,index)=><option key={index} value={index}>{s.title||"Untitled section"}</option>)}</select></label><label style={{display:"block",marginTop:12}}>Curatorial annotation<textarea value={document.annotations[record.id]??""} maxLength={3000} onChange={e=>setDocument({...document,annotations:{...document.annotations,[record.id]:e.target.value}})} rows={2} style={{display:"block",width:"100%",font:"inherit"}}/></label></fieldset>)}
    <fieldset><legend>Relationships within this collection</legend>{document.relationships.map((relation,index)=><div key={index} style={{display:"grid",gap:8,marginBottom:16}}><label>From<select value={relation.from} onChange={e=>setDocument({...document,relationships:document.relationships.map((r,i)=>i===index?{...r,from:e.target.value}:r)})}>{records.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>To<select value={relation.to} onChange={e=>setDocument({...document,relationships:document.relationships.map((r,i)=>i===index?{...r,to:e.target.value}:r)})}>{records.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Your curatorial explanation<textarea value={relation.note} maxLength={2000} onChange={e=>setDocument({...document,relationships:document.relationships.map((r,i)=>i===index?{...r,note:e.target.value}:r)})}/></label><button type="button" onClick={()=>setDocument({...document,relationships:document.relationships.filter((_,i)=>i!==index)})}>Remove relationship</button></div>)}<button type="button" disabled={records.length<2||document.relationships.length>=100} onClick={()=>setDocument({...document,relationships:[...document.relationships,{from:records[0].id,to:records[1].id,note:""}]})}>Add a relationship</button><p>Curatorial interpretations are shared with this collection. Propose evidence-backed archive relationships separately for review.</p></fieldset>
    <div><a href={`/api/knowledge/collections/${id}?export=bibtex`}>Export research list · BibTeX</a> · <a href={`/api/knowledge/collections/${id}?export=ris`}>RIS</a></div>
    <button className="ared-btn ared-btn--primary" disabled={!ready||busy}>{busy?<LineLoader inline size={18} label="Saving" />:"Save collection writing"}</button><p role="status">{message}</p>
  </form></details>;
}
