import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
async function post(path,body,headers={}){return fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});}
const records=JSON.parse(fs.readFileSync('data/catalogue/catalogue-records.json','utf8'));const restricted=records.find(r=>r.communityAuthorityRequired);
const r=await post('/api/for-you',{page:1,seed:'native-http',session:[],seen:[]});assert.equal(r.status,200);const a=await r.json();assert.ok(a.items.length>0);assert.ok(a.items.every(i=>i.why && !records.some(r=>r.id===i.id && (!r.publicVisibility||r.communityAuthorityRequired))));console.log('PASS cold start and cultural-access filter',a.items.length,a.quality);
const next=await (await post('/api/for-you',{page:2,seed:a.seed,seen:a.items.map(i=>i.id)})).json();assert.ok(next.items.every(i=>!a.items.some(x=>x.id===i.id)));console.log('PASS pagination excludes seen IDs');
const less=a.items[0].id;const negative=await (await post('/api/for-you',{page:1,seed:a.seed,feedback:{less:[less]}})).json();assert.ok(!negative.items.some(i=>i.id===less));assert.ok(negative.items.length);console.log('PASS anonymous feedback affects session, keeps browsing open');
assert.equal((await post('/api/recommendations/events',{type:'more',id:less,sessionId:'test'})).status,401);assert.equal((await post('/api/recommendations/events',{type:'more',id:less,sessionId:'test'},{Origin:'https://untrusted.invalid'})).status,403);assert.equal((await post('/api/recommendations/events',{type:'record_open',id:restricted.id,sessionId:'test'})).status,404);assert.equal((await post('/api/recommendations/events',{type:'bad',id:less,sessionId:'test'})).status,400);console.log('PASS feedback authentication, origin, validation, restricted-record rejection');
const related=await (await post('/api/for-you/similar',{item:{id:'ARED-GH-00055',title:'Gold Weight'},seen:[]})).json();assert.ok(related.items.length);assert.ok(related.items.every(i=>i.why.includes('shared metadata')&&!records.some(r=>r.id===i.id && r.communityAuthorityRequired)));console.log('PASS metadata-related records and current access');
const suggestions=await (await fetch(base+'/api/recommendations/suggestions')).json();assert.deepEqual(suggestions,{profiles:[],collections:[]});console.log('PASS honest guest suggestions');

const blockedRelated=await (await post('/api/for-you/similar',{item:{id:restricted.id,title:restricted.title},seen:[]})).json();assert.deepEqual(blockedRelated.items,[]);console.log('PASS restricted related seed cannot use provider fallback');
