import type { HistoricalEntry } from "./types";

/** Curated historical and documentary entries for Ghana graphic design history */
export const HISTORICAL_ENTRIES: HistoricalEntry[] = [
  // ── Period overviews ──────────────────────────────────────────────────────
  {
    title: "Indigenous visual systems before colonial rule",
    record_type: "historical overview",
    period_id: "P1",
    period_label: "Visual systems before colonial rule",
    visual_system_id: "V1",
    visual_system_label: "Land, cosmology and authority",
    date_display: "pre-1471",
    date_start: "1000",
    date_end: "1470",
    source_facts:
      'Scholarly accounts of pre-colonial Ghana describe long-established Akan, Ga, Ewe and related visual languages in gold regalia, stamped and woven cloth, shrine arts, proverbial weights and memorial sculpture. R. S. Rattray\'s early ethnographic work and subsequent museum catalogues document these as communicative systems rather than "decorative" artefacts alone.',
    ared_interpretation:
      "ARED frames pre-colonial Ghanaian visual culture as graphic communication: pattern, symbol and form carried authority, memory and social identity before European print arrived on the coast.",
    historical_significance:
      "Foundation period for adinkra, kente, goldweights, nsodie and related systems that later interact with colonial and post-independence design.",
    primary_source_name: "R. S. Rattray, Ashanti (1923) — via Internet Archive",
    primary_source_url: "https://archive.org/details/ashanti0000ratt",
    verification_status: "partially_verified",
    tags: "overview; pre-colonial; visual systems",
  },
  {
    title: "Coastal contact and transcultural visual exchange",
    record_type: "historical overview",
    period_id: "P2",
    period_label: "Coastal contact and transcultural exchange, c. 1471–1874",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "1471–1874",
    date_start: "1471",
    date_end: "1874",
    region: "Ghana",
    locality: "Elmina; Cape Coast; Accra",
    source_facts:
      "European fortifications and trade on the Gold Coast from the late 15th century introduced new materials, pictorial forms and literacy alongside existing African visual systems. Castle signage, trade documents, religious prints and imported goods entered local visual economies documented in coastal histories and museum collections.",
    ared_interpretation:
      "This period is not merely 'pre-colonial background' but an active era of visual translation between Atlantic trade, mission activity and indigenous makers.",
    primary_source_name: "UNESCO World Heritage — Forts and Castles, Volta, Greater Accra",
    primary_source_url: "https://whc.unesco.org/en/list/34/",
    verification_status: "partially_verified",
    tags: "overview; coastal; trade; castles",
  },
  {
    title: "Colonial print culture and institutional design",
    record_type: "historical overview",
    period_id: "P3",
    period_label: "Colonial print and institutional design, 1874–1945",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "1874–1945",
    date_start: "1874",
    date_end: "1945",
    source_facts:
      "Formal British colonial administration after 1874 expanded government printing, missionary publishing, commercial advertising and vernacular literacy. Gold Coast newspapers, schoolbooks, postage, currency and railway publicity created new public graphic formats documented in national archives and library collections.",
    ared_interpretation:
      "Colonial print did not replace indigenous visual systems; it layered bureaucratic, missionary and commercial genres onto existing cloth, proverb and performance cultures.",
    primary_source_name: "British Library — Gold Coast collections",
    primary_source_url: "https://www.bl.uk/collection-guides/gold-coast",
    verification_status: "partially_verified",
    tags: "overview; colonial; print",
  },
  {
    title: "Anticolonial and independence visual culture",
    record_type: "historical overview",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1945–1966",
    date_start: "1945",
    date_end: "1966",
    source_facts:
      "Ghana's independence movement mobilised photography, posters, newspapers, flags, stamps and public ceremony as political communication. Kwame Nkrumah's Convention People's Party and allied cultural workers produced a recognisable independence-era visual field documented in national histories and museum holdings.",
    ared_interpretation:
      "Independence was visually staged: new symbols, portraits and campaign graphics turned political aspiration into designed public culture.",
    primary_source_name: "Ghana Independence — Encyclopaedia Britannica",
    primary_source_url: "https://www.britannica.com/place/Ghana/The-national-revolution-and-the-republic",
    verification_status: "partially_verified",
    tags: "overview; independence; nationalism",
  },
  {
    title: "Post-independence public and popular graphics",
    record_type: "historical overview",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1966–1992",
    date_start: "1966",
    date_end: "1992",
    source_facts:
      "After 1966 Ghana saw changing state media, commercial advertising, record sleeves, cinema publicity, festival arts and workshop-based design education. Photographers, sign painters and state printers shaped everyday visual life in Accra, Kumasi, Takoradi and regional towns.",
    ared_interpretation:
      "Popular graphics in this era include both state-sponsored modernisation imagery and grassroots sign, music and market visual cultures.",
    primary_source_name: "James Barnor archive — Autograph ABP",
    primary_source_url: "https://autograph.org.uk/exhibitions/james-barnor",
    verification_status: "source_located",
    tags: "overview; post-independence; popular culture",
  },
  {
    title: "Democratic, digital and diasporic design since 1992",
    record_type: "historical overview",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V7",
    visual_system_label: "Digital, diasporic and contemporary design",
    date_display: "1992–present",
    date_start: "1992",
    date_end: "2026",
    source_facts:
      "Ghana's return to multi-party democracy coincided with expanded commercial branding, broadcast graphics, digital media, street art festivals and diasporic design networks. Contemporary Ghanaian designers work across Accra, Kumasi, London and global platforms.",
    ared_interpretation:
      "Recent Ghanaian design is simultaneously local, pan-African and global — shaped by social media, festivals and international art markets.",
    primary_source_name: "Chale Wote Street Art Festival",
    primary_source_url: "https://chalewotefest.com/",
    verification_status: "source_located",
    tags: "overview; contemporary; digital",
  },

  // ── Indigenous visual systems (P1–P2) ─────────────────────────────────────
  {
    title: "Adinkra stamped cloth tradition",
    record_type: "documented practice",
    period_id: "P1",
    period_label: "Visual systems before colonial rule",
    visual_system_id: "V3",
    visual_system_label: "Cloth, pattern and social identity",
    date_display: "documented from at least 19th century; older origins debated",
    date_start: "1800",
    date_end: "2026",
    community_or_culture: "Akan peoples; associated with Bono and Asante histories",
    locality: "Bono-Ahafo; Kumasi region",
    object_type: "textile practice",
    medium: "cotton cloth; carved calabash stamps; adinkra dye",
    source_facts:
      'Adinkra is an Akan cloth tradition stamped with symbolic motifs, historically associated with funerary and ceremonial use. Named symbols such as Gye Nyame are documented in Akan scholarship and widely reproduced in later Ghanaian graphic design. UNESCO and Ghanaian cultural agencies describe adinkra as intangible heritage linked to Bono origins.',
    ared_interpretation:
      "Adinkra functions as a proto-graphic system: repeatable symbols with proverbial meanings, later adapted into logos, typography and national branding.",
    historical_significance:
      "One of Ghana's most exported visual languages into contemporary design and diaspora identity graphics.",
    primary_source_name: "UNESCO Intangible Cultural Heritage — Adinkra (related Akan traditions)",
    primary_source_url: "https://ich.unesco.org/",
    secondary_sources: "Kwaku Osei-Bonsu; Akan symbol dictionaries",
    verification_status: "partially_verified",
    uncertainties: "exact origin dates and individual early makers often unrecorded",
    tags: "adinkra; textile; Akan; symbol",
  },
  {
    title: "Kente woven cloth as pattern communication",
    record_type: "documented practice",
    period_id: "P1",
    period_label: "Visual systems before colonial rule",
    visual_system_id: "V3",
    visual_system_label: "Cloth, pattern and social identity",
    date_display: "centuries-old; widely documented 19th–20th century",
    date_start: "1700",
    date_end: "2026",
    community_or_culture: "Asante; Ewe; related weaving communities",
    locality: "Kumasi; Bonwire; Agbozume",
    object_type: "textile weaving",
    medium: "silk; cotton; strip weave",
    source_facts:
      "Kente is a strip-woven prestige cloth associated especially with Asante and Ewe makers. Named patterns carry social meaning and are worn at ceremonies of status. Ghanaian museums, Bonwire community accounts and textile scholarship document kente as a coded visual language rather than purely decorative cloth.",
    ared_interpretation:
      "Kente patterns operate like a designed vocabulary of colour and motif — a wearable graphic system central to Ghanaian public ceremony.",
    primary_source_name: "Bonwire Kente Museum / Ghana tourism documentation",
    primary_source_url: "https://www.ghana.travel/places-to-visit/regions/ashanti-region/",
    verification_status: "partially_verified",
    tags: "kente; textile; Asante; Ewe; weaving",
  },
  {
    title: "Akan goldweights (abrammuo) as proverbial graphic forms",
    record_type: "documented practice",
    period_id: "P2",
    period_label: "Coastal contact and transcultural exchange, c. 1471–1874",
    visual_system_id: "V1",
    visual_system_label: "Land, cosmology and authority",
    date_display: "17th–20th century (museum dating)",
    date_start: "1600",
    date_end: "1950",
    community_or_culture: "Akan; Asante",
    object_type: "metal weights",
    medium: "brass; copper alloy",
    source_facts:
      "Akan goldweights were used in trade measurement and cast or modelled in figurative and geometric forms referencing proverbs and social concepts. Major museums including the British Museum and Metropolitan Museum hold extensive Ghana-related goldweight collections with accession documentation.",
    ared_interpretation:
      "Goldweights are miniature designed objects: visual shorthand for proverb, satire and authority within Akan communicative culture.",
    primary_source_name: "British Museum collection — Akan goldweights",
    primary_source_url: "https://www.britishmuseum.org/collection/search?keyword=akan+goldweight",
    verification_status: "partially_verified",
    tags: "goldweight; Akan; proverb; brass",
  },
  {
    title: "Nsodie (memorial terracotta heads)",
    record_type: "documented practice",
    period_id: "P2",
    period_label: "Coastal contact and transcultural exchange, c. 1471–1874",
    visual_system_id: "V2",
    visual_system_label: "Memory, proverb and performance",
    date_display: "17th–19th century (typical museum dating)",
    date_start: "1600",
    date_end: "1900",
    community_or_culture: "Akan peoples",
    object_type: "ceramic sculpture",
    medium: "terracotta",
    source_facts:
      "Nsodie are Akan memorial heads placed at sacred burial sites to honour the dead. Terracotta examples are documented in Ghana and in museum collections worldwide. Met and Cleveland Museum accession records describe culture, medium and regional attribution.",
    ared_interpretation:
      "Memorial heads embody designed presence — portraiture without individual likeness conventions of European print portraiture.",
    primary_source_name: "Metropolitan Museum — Akan memorial head records",
    primary_source_url: "https://www.metmuseum.org/art/collection/search?q=nsodie",
    verification_status: "partially_verified",
    tags: "nsodie; Akan; terracotta; memorial",
  },
  {
    title: "Fante Asafo company flags (frankaa)",
    record_type: "documented practice",
    period_id: "P2",
    period_label: "Coastal contact and transcultural exchange, c. 1471–1874",
    visual_system_id: "V2",
    visual_system_label: "Memory, proverb and performance",
    date_display: "19th century–present",
    date_start: "1800",
    date_end: "2026",
    community_or_culture: "Fante; coastal Ghana",
    locality: "Central Region; Cape Coast; Anomabo",
    object_type: "appliqué flag",
    medium: "cotton cloth; appliqué; stitch",
    source_facts:
      "Asafo flags belong to Fante military companies (asafo) along Ghana's coast. Flags combine figurative appliqué, proverb and company identity. Collections at the Fowler Museum, Brooklyn Museum and Ghanaian community archives document their role in public performance and rivalry.",
    ared_interpretation:
      "Asafo flags are a major Ghanaian graphic genre: designed cloth banners for collective identity, satire and historical narrative.",
    primary_source_name: "Fowler Museum — Asafo flags collection",
    primary_source_url: "https://fowler.ucla.edu/collections/asafo-flags/",
    verification_status: "partially_verified",
    tags: "asafo; flag; Fante; appliqué; proverb",
  },
  {
    title: "Ga mfrankaa (posuban shrine banners)",
    record_type: "documented practice",
    period_id: "P2",
    period_label: "Coastal contact and transcultural exchange, c. 1471–1874",
    visual_system_id: "V2",
    visual_system_label: "Memory, proverb and performance",
    date_display: "19th–20th century",
    date_start: "1800",
    date_end: "2000",
    community_or_culture: "Ga peoples",
    locality: "Accra; Teshie; Labadi",
    object_type: "shrine banner",
    medium: "cloth; paint; appliqué",
    source_facts:
      "Ga posuban (military/shrine posts) and associated banners (mfrankaa) combine figurative painting and cloth in urban Accra neighbourhoods. Ethnographic and community documentation describe them as public religious and historical graphics.",
    ared_interpretation:
      "Ga shrine banners share coastal Ghana's tradition of designed cloth as public narrative — parallel to Asafo but within Ga religious urbanism.",
    primary_source_name: "Ghana Museums and Monuments Board",
    primary_source_url: "https://gmmb.gov.gh/",
    verification_status: "source_located",
    tags: "Ga; posuban; mfrankaa; Accra; shrine",
  },
  {
    title: "Ewe kente and woven identity",
    record_type: "documented practice",
    period_id: "P2",
    period_label: "Coastal contact and transcultural exchange, c. 1471–1874",
    visual_system_id: "V3",
    visual_system_label: "Cloth, pattern and social identity",
    date_display: "19th–20th century",
    date_start: "1800",
    date_end: "2026",
    community_or_culture: "Ewe peoples",
    locality: "Volta Region; Agbozume",
    object_type: "textile weaving",
    medium: "cotton; rayon; strip weave",
    source_facts:
      "Ewe kente traditions are documented in Volta Region weaving centres such as Agbozume. Museum textile records attribute wrappers and prestige cloths to Ewe makers with distinct pattern repertoires from Asante kente.",
    ared_interpretation:
      "Ewe weaving expands Ghana's graphic history beyond a single 'kente' narrative — multiple designed cloth systems coexist.",
    primary_source_name: "Metropolitan Museum — Ewe wrapper records",
    primary_source_url: "https://www.metmuseum.org/art/collection/search?q=ewe+ghana+textile",
    verification_status: "partially_verified",
    tags: "Ewe; kente; Volta; textile",
  },

  // ── Colonial print & institutions (P3) ────────────────────────────────────
  {
    title: "Basel Mission press and early vernacular printing",
    record_type: "institution",
    period_id: "P3",
    period_label: "Colonial print and institutional design, 1874–1945",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "19th century",
    date_start: "1828",
    date_end: "1918",
    locality: "Akropong; Osu",
    institution_or_collection: "Basel Mission",
    object_type: "mission printing",
    medium: "letterpress; religious tract; schoolbook",
    source_facts:
      "The Basel Mission established printing and literacy work on the Gold Coast from the 19th century, producing religious and educational materials in local and European languages. Mission archives and Ghanaian church histories document early typographic and illustrated book production.",
    ared_interpretation:
      "Mission printing introduced European typographic layout into Ghana while also supporting local language literacy — a foundational colonial-era graphic infrastructure.",
    primary_source_name: "Basel Mission Archive (overview)",
    primary_source_url: "https://www.bmarchives.org/",
    verification_status: "source_located",
    tags: "Basel Mission; print; mission; Akropong",
  },
  {
    title: "Gold Coast Government Printing Department",
    record_type: "institution",
    period_id: "P3",
    period_label: "Colonial print and institutional design, 1874–1945",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "colonial era",
    date_start: "1874",
    date_end: "1957",
    locality: "Accra",
    institution_or_collection: "Gold Coast colonial administration",
    object_type: "government printing",
    medium: "official gazette; form; poster",
    source_facts:
      "Colonial Gold Coast administration relied on government printing for gazettes, legislation, tax forms, public notices and educational materials. National archives and library finding aids reference Government Printer publications as core bureaucratic graphic formats.",
    ared_interpretation:
      "State paperwork is a designed genre: layout, seal and typography communicated imperial authority long before independence branding.",
    primary_source_name: "Public Records and Archives Administration Department (PRAAD) Ghana",
    primary_source_url: "https://praad.gov.gh/",
    verification_status: "source_located",
    tags: "government print; colonial; gazette; Accra",
  },
  {
    title: "Gold Coast Gazette and early newspapers",
    record_type: "publication genre",
    period_id: "P3",
    period_label: "Colonial print and institutional design, 1874–1945",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "19th–20th century",
    date_start: "1850",
    date_end: "1957",
    object_type: "newspaper",
    medium: "letterpress newsprint",
    source_facts:
      "Gold Coast newspapers including official gazettes and commercial papers created recurring masthead, headline and advertisement layouts. Library and newspaper archive holdings document the emergence of a local press culture before independence.",
    ared_interpretation:
      "Newspaper design trained readers in daily graphic formats — news hierarchy, advertising blocks and political cartoons.",
    primary_source_name: "British Library Newspapers — Africa",
    primary_source_url: "https://www.bl.uk/collection-guides/newspapers",
    verification_status: "source_located",
    tags: "newspaper; Gold Coast; press; gazette",
  },
  {
    title: "Railway and colonial commercial advertising",
    record_type: "documented practice",
    period_id: "P3",
    period_label: "Colonial print and institutional design, 1874–1945",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "early–mid 20th century",
    date_start: "1900",
    date_end: "1960",
    object_type: "advertising poster",
    medium: " lithograph; offset print",
    source_facts:
      "Gold Coast railway expansion and consumer imports produced illustrated timetables, travel posters and product advertisements aimed at urban and coastal audiences. Archive ephemera and museum collections preserve examples of early commercial graphics.",
    ared_interpretation:
      "Colonial advertising introduced illustrated persuasion — a bridge to post-war Accra studio photography and calendar advertising.",
    primary_source_name: "Ghana Railway history — academic and archive sources",
    primary_source_url: "https://praad.gov.gh/",
    verification_status: "source_located",
    tags: "railway; advertising; colonial; poster",
  },
  {
    title: "Imported wax-print cloth (Dutch block and roller print)",
    record_type: "documented practice",
    period_id: "P3",
    period_label: "Colonial print and institutional design, 1874–1945",
    visual_system_id: "V3",
    visual_system_label: "Cloth, pattern and social identity",
    date_display: "late 19th–20th century",
    date_start: "1890",
    date_end: "2026",
    object_type: "printed textile",
    medium: "cotton wax print",
    source_facts:
      "Factory-printed wax cloth from European firms (including Vlisco and related suppliers) became central to West African dress and naming cultures. Ghanaian markets renamed patterns; ATL, GTP and other firms later produced region-specific designs documented in textile industry histories.",
    ared_interpretation:
      "Wax print is a designed medium shaped by Ghanaian consumers — pattern names, social meaning and fashion cycles constitute a popular graphic economy.",
    primary_source_name: "Vlisco company history",
    primary_source_url: "https://www.vlisco.com/about-us/history/",
    verification_status: "partially_verified",
    tags: "wax print; textile; Vlisco; GTP; fashion",
  },

  // ── Independence era state design (P4) ────────────────────────────────────
  {
    title: "National flag of Ghana",
    record_type: "state symbol",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "adopted 1957",
    date_start: "1957",
    date_end: "2026",
    creator_or_authority: "Theodosia Okoh (widely credited designer)",
    creator_role: "designer",
    locality: "Accra",
    object_type: "flag",
    medium: "textile; horizontal tricolour",
    source_facts:
      "Ghana's flag — red, gold and green horizontal stripes with a black star — was adopted at independence in 1957. Ghanaian and international sources credit artist Theodosia Okoh with the design. The black star references Marcus Garvey's Black Star Line and Ghana's leadership in African independence.",
    ared_interpretation:
      "The flag is Ghana's foundational republic graphic: colour symbolism and star motif reused across stamps, coins, sports kits and diaspora identity design.",
    historical_significance: "Primary national symbol of the first sub-Saharan African colony to achieve independence.",
    primary_source_name: "Government of Ghana — national symbols",
    primary_source_url: "https://www.ghana.gov.gh/about-ghana/national-symbols/",
    verification_status: "partially_verified",
    tags: "flag; independence; Theodosia Okoh; national symbol",
  },
  {
    title: "Coat of arms of Ghana",
    record_type: "state symbol",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "adopted 4 March 1957",
    date_start: "1957",
    date_end: "2026",
    creator_or_authority: "Nii Amon Kotei (lead artist, documented)",
    creator_role: "designer",
    object_type: "heraldic emblem",
    medium: "illustration; official seal",
    source_facts:
      "Ghana's coat of arms was adopted on 4 March 1957, featuring a shield with cross, castle, cocoa tree and mine, supported by eagles and bearing the motto FREEDOM AND JUSTICE. Artist Nii Amon Kotei is widely documented as principal designer among a committee of artists.",
    ared_interpretation:
      "The coat of arms codified resource and history imagery into a single official pictogram used on documents, currency and state architecture.",
    primary_source_name: "Government of Ghana — national symbols",
    primary_source_url: "https://www.ghana.gov.gh/about-ghana/national-symbols/",
    verification_status: "partially_verified",
    tags: "coat of arms; Nii Amon Kotei; heraldry; independence",
  },
  {
    title: "Kwame Nkrumah — political portraiture and campaign graphics",
    record_type: "person",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1940s–1966",
    date_start: "1947",
    date_end: "1966",
    creator_or_authority: "Kwame Nkrumah",
    creator_role: "political leader / subject of visual culture",
    object_type: "political portrait; poster",
    medium: "photography; print; banner",
    source_facts:
      "Kwame Nkrumah, first Prime Minister and President of Ghana, was one of the most reproduced political figures in West African visual culture. Photographs, posters, stamps and public monuments circulated his image during CPP campaigns and independence celebrations.",
    ared_interpretation:
      "Nkrumah's visual presence exemplifies designed political charisma — portrait, gesture and colour deployed for mass mobilisation.",
    primary_source_name: "Kwame Nkrumah — Encyclopaedia Britannica",
    primary_source_url: "https://www.britannica.com/biography/Kwame-Nkrumah",
    verification_status: "partially_verified",
    tags: "Nkrumah; politics; portrait; CPP",
  },
  {
    title: "Convention People's Party (CPP) campaign materials",
    record_type: "documented practice",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1950s",
    date_start: "1949",
    date_end: "1966",
    institution_or_collection: "Convention People's Party",
    object_type: "political ephemera",
    medium: "poster; leaflet; badge",
    source_facts:
      "The CPP used printed ephemera, photographs and public spectacle in the Positive Action era and 1951/1956 elections leading to independence. Political history archives and museum collections hold campaign badges, cloth and printed slogans.",
    ared_interpretation:
      "CPP graphics linked anti-colonial rhetoric to repeatable visual motifs — a template for later Ghanaian party political design.",
    primary_source_name: "Ghana independence historical accounts",
    primary_source_url: "https://www.ghana.gov.gh/about-ghana/history/",
    verification_status: "source_located",
    tags: "CPP; campaign; politics; independence",
  },
  {
    title: "Ghana Post independence stamp issues",
    record_type: "publication series",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "from 1957",
    date_start: "1957",
    date_end: "2026",
    institution_or_collection: "Ghana Post",
    object_type: "postage stamp",
    medium: "engraving; offset miniature design",
    source_facts:
      "Ghana's postal authority issued stamps from independence onward depicting leaders, industry, culture and events. Stamp catalogues and philatelic archives document Ghana as an early post-colonial issuer of national commemorative miniature graphics.",
    ared_interpretation:
      "Stamps functioned as everyday state publishing — small designed surfaces reaching households and international post.",
    primary_source_name: "Stanley Gibbons / Colnect Ghana stamps catalogue",
    primary_source_url: "https://www.colnect.com/en/stamps/list/country/82-Ghana",
    verification_status: "source_located",
    tags: "stamp; Ghana Post; philately; state design",
  },
  {
    title: "Theodosia Okoh",
    record_type: "person",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1922–2015",
    date_start: "1922",
    date_end: "2015",
    creator_or_authority: "Theodosia Okoh",
    creator_role: "artist; teacher; flag designer",
    object_type: "biographical authority",
    source_facts:
      "Theodosia Okoh (1922–2015) was a Ghanaian artist and teacher widely credited with designing Ghana's national flag in 1957. Ghanaian government and cultural obituaries document her role in national symbol design and sports administration.",
    ared_interpretation:
      "Okoh anchors Ghana's design history in named female authorship of the republic's most visible graphic.",
    primary_source_name: "Theodosia Okoh — Wikipedia (cross-check with Ghana gov sources)",
    primary_source_url: "https://en.wikipedia.org/wiki/Theodosia_Okoh",
    verification_status: "partially_verified",
    tags: "Theodosia Okoh; designer; flag; person",
  },
  {
    title: "Nii Amon Kotei",
    record_type: "person",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1915–2011",
    date_start: "1915",
    date_end: "2011",
    creator_or_authority: "Nii Amon Kotei",
    creator_role: "artist; heraldic designer",
    source_facts:
      "Nii Amon Kotei (1915–2011) was a Ghanaian artist documented as lead designer of the national coat of arms in 1957. State honours and obituaries in Ghanaian press record his contribution to independence-era official imagery.",
    ared_interpretation:
      "Kotei's work shows how fine artists were recruited to build bureaucratic visual identity at independence.",
    primary_source_name: "Ghana national symbols documentation",
    primary_source_url: "https://www.ghana.gov.gh/about-ghana/national-symbols/",
    verification_status: "partially_verified",
    tags: "Nii Amon Kotei; coat of arms; artist; person",
  },

  // ── Photography, advertising & popular graphics (P4–P5) ───────────────────
  {
    title: "James Barnor — Ever Young studio and street photography",
    record_type: "person",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1950s–1970s (Ghana period); active to present",
    date_start: "1929",
    date_end: "2026",
    creator_or_authority: "James Barnor",
    creator_role: "photographer",
    locality: "Accra; London",
    object_type: "photography studio",
    medium: "film photography; studio portrait; press",
    source_facts:
      "James Barnor (born 1929) opened the Ever Young studio in Accra and worked for Drum magazine and commercial clients including Agip calendar campaigns. Retrospectives by Autograph, Galerie Clémentine de la Féronnière and museum acquisitions document his role in Ghanaian and diasporic popular photography.",
    ared_interpretation:
      "Barnor's studio portraits and advertising work are core Ghanaian graphic history — fashion, pose and backdrop as designed self-presentation.",
    primary_source_name: "Autograph — James Barnor",
    primary_source_url: "https://autograph.org.uk/exhibitions/james-barnor",
    verification_status: "partially_verified",
    tags: "James Barnor; photography; Ever Young; Accra",
  },
  {
    title: "Drum magazine West Africa — Ghana coverage",
    record_type: "publication",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1950s–1970s",
    date_start: "1951",
    date_end: "1980",
    object_type: "magazine",
    medium: "photography; offset magazine layout",
    source_facts:
      "Drum magazine covered fashion, politics and urban culture across West and East Africa with strong Ghanaian photographic content. Layout, headline design and photo essays shaped regional popular modernity documented in media histories.",
    ared_interpretation:
      "Drum is a transnational graphic platform where Ghanaian photographers and subjects entered pan-African visual culture.",
    primary_source_name: "Drum magazine historical overview",
    primary_source_url: "https://www.britannica.com/topic/Drum-magazine",
    verification_status: "source_located",
    tags: "Drum; magazine; photography; popular press",
  },
  {
    title: "Daily Graphic newspaper",
    record_type: "publication",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "founded 1950",
    date_start: "1950",
    date_end: "2026",
    institution_or_collection: "Graphic Communications Group Ltd",
    locality: "Accra",
    object_type: "daily newspaper",
    medium: "newsprint; phototypeset; digital (later)",
    source_facts:
      "The Daily Graphic, founded in 1950, is one of Ghana's longest-running daily newspapers. Its masthead, photo layout and advertising columns constitute a daily designed interface of national news.",
    ared_interpretation:
      "Daily Graphic represents the institutionalisation of Ghanaian news design after independence.",
    primary_source_name: "Graphic Online — About",
    primary_source_url: "https://www.graphic.com.gh/",
    verification_status: "partially_verified",
    tags: "Daily Graphic; newspaper; Accra; press",
  },
  {
    title: "Ghanaian Times newspaper",
    record_type: "publication",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "founded 1957",
    date_start: "1957",
    date_end: "2026",
    institution_or_collection: "New Times Corporation",
    object_type: "daily newspaper",
    medium: "newsprint",
    source_facts:
      "The Ghanaian Times was established in 1957 as a state-linked daily paper in the independence era. It forms part of Ghana's mid-century public print landscape alongside the Daily Graphic.",
    ared_interpretation:
      "Competing mastheads and photo layouts shaped Ghanaian readers' visual habits in the early republic.",
    primary_source_name: "Ghanaian Times",
    primary_source_url: "https://www.ghanaiantimes.com.gh/",
    verification_status: "source_located",
    tags: "Ghanaian Times; newspaper; state media",
  },
  {
    title: "Hand-painted cinema and concert posters (Accra)",
    record_type: "documented practice",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1970s–1990s",
    date_start: "1970",
    date_end: "1995",
    locality: "Accra; Kumasi",
    object_type: "hand-painted poster",
    medium: "oil paint on flour sack / board",
    source_facts:
      "Hand-painted film and music posters flourished in Ghanaian cities, especially for mobile cinema and concert promotion. Scholarly articles and collector documentation describe bold figurative painting styles associated with artists such as Leonardo da Vinci Opoku and regional sign-painting traditions.",
    ared_interpretation:
      "Ghanaian cinema posters are an internationally recognised popular graphic genre — painterly, serial and locally authored.",
    primary_source_name: "Karun Thakar collection / academic studies of Ghanaian film posters",
    primary_source_url: "https://www.karunthakar.com/",
    verification_status: "source_located",
    uncertainties: "individual artist attributions vary by poster; dating often approximate",
    tags: "cinema poster; hand-painted; Accra; popular art",
  },
  {
    title: "Highlife record sleeve and music graphics",
    record_type: "documented practice",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1950s–1980s",
    date_start: "1950",
    date_end: "1990",
    object_type: "record sleeve",
    medium: "vinyl LP sleeve; photography; typography",
    source_facts:
      "Highlife and later Afro-pop releases on labels such as Philips, Decca and local presses used photography, lettering and colour blocking on sleeves. Discography archives and collector communities document Ghana as a major West African music packaging market.",
    ared_interpretation:
      "Record sleeves carried performer image, dance fashion and studio typography into households — parallel to Barnor's studio work.",
    primary_source_name: "Discogs — Ghanaian releases",
    primary_source_url: "https://www.discogs.com/search/?country=Ghana",
    verification_status: "source_located",
    tags: "highlife; music; record sleeve; vinyl",
  },
  {
    title: "Kane Kwei — figurative coffin workshop (popular sculpture as design)",
    record_type: "person",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1950s–1990s",
    date_start: "1922",
    date_end: "1992",
    creator_or_authority: "Kane Kwei (Seth Kane Kwei workshop tradition)",
    creator_role: "sculptor; workshop founder",
    locality: "Teshie; Accra",
    object_type: "figurative coffin",
    medium: "wood; paint",
    source_facts:
      "Kane Kwei pioneered Ga figurative coffins shaped like objects reflecting the deceased's profession or status. Documented by scholars and museums worldwide, the Teshie workshop tradition is a major Ghanaian popular design export.",
    ared_interpretation:
      "Fantasy coffins are designed objects at life scale — humour, profession and status rendered as public funeral graphics.",
    primary_source_name: "Centre Pompidou / museum documentation of Kane Kwei coffins",
    primary_source_url: "https://www.centrepompidou.fr/en/ressources/oeuvre/cOR7n88",
    verification_status: "partially_verified",
    tags: "Kane Kwei; Ga; coffin; Teshie; popular art",
  },

  // ── Education & institutions (P4–P6) ──────────────────────────────────────
  {
    title: "Kwame Nkrumah University of Science and Technology — Faculty of Art",
    record_type: "institution",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V7",
    visual_system_label: "Digital, diasporic and contemporary design",
    date_display: "College of Art established 1961",
    date_start: "1961",
    date_end: "2026",
    locality: "Kumasi",
    institution_or_collection: "KNUST Faculty of Art",
    object_type: "art and design school",
    source_facts:
      "KNUST's Faculty of Art (formerly College of Art) was established in 1961 within the Kumasi College of Technology, training generations of Ghanaian painters, sculptors, textile artists and designers. University histories credit it as a major institutional hub for modern Ghanaian visual education.",
    ared_interpretation:
      "KNUST formalised studio pedagogy that bridged indigenous craft, modernism and later graphic design professions.",
    primary_source_name: "KNUST Faculty of Art",
    primary_source_url: "https://art.knust.edu.gh/",
    verification_status: "partially_verified",
    tags: "KNUST; art school; Kumasi; education",
  },
  {
    title: "University of Ghana — Institute of African Studies and Legon art programmes",
    record_type: "institution",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V4",
    visual_system_label: "Print, colonial rule and public culture",
    date_display: "1960s–present",
    date_start: "1961",
    date_end: "2026",
    locality: "Legon; Accra",
    institution_or_collection: "University of Ghana",
    object_type: "research institute; art education",
    source_facts:
      "The Institute of African Studies at Legon, founded in 1961, supported documentation of Ghanaian cultural production alongside university art and archaeology programmes that shaped scholarly and curatorial approaches to local visual history.",
    ared_interpretation:
      "Legon institutionalised research on Ghanaian visual culture — connecting field documentation to national archives and museums.",
    primary_source_name: "University of Ghana — Institute of African Studies",
    primary_source_url: "https://ias.ug.edu.gh/",
    verification_status: "source_located",
    tags: "Legon; University of Ghana; African Studies; research",
  },
  {
    title: "Ghana Museums and Monuments Board (GMMB)",
    record_type: "institution",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V1",
    visual_system_label: "Land, cosmology and authority",
    date_display: "1957–present",
    date_start: "1957",
    date_end: "2026",
    institution_or_collection: "Ghana Museums and Monuments Board",
    locality: "Accra",
    object_type: "national museum authority",
    source_facts:
      "GMMB oversees public museums and heritage sites including the National Museum of Ghana and coastal forts. It holds collections central to documenting Ghanaian material and visual culture for public interpretation.",
    ared_interpretation:
      "GMMB is the primary state custodian of objects that anchor Ghana's designed heritage — from adinkra to independence ephemera.",
    primary_source_name: "Ghana Museums and Monuments Board",
    primary_source_url: "https://gmmb.gov.gh/",
    verification_status: "partially_verified",
    tags: "GMMB; museum; heritage; Accra",
  },
  {
    title: "National Museum of Ghana, Accra",
    record_type: "institution",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V1",
    visual_system_label: "Land, cosmology and authority",
    date_display: "opened 1957",
    date_start: "1957",
    date_end: "2026",
    locality: "Accra",
    institution_or_collection: "National Museum of Ghana",
    object_type: "museum",
    source_facts:
      "The National Museum of Ghana opened in Accra in 1957, displaying archaeology, ethnography and history collections. It is a key public site for encountering Ghanaian visual and material culture.",
    ared_interpretation:
      "Museum display itself is a designed medium — how Ghana narrates its visual past to citizens and visitors.",
    primary_source_name: "Ghana Museums and Monuments Board",
    primary_source_url: "https://gmmb.gov.gh/national-museum/",
    verification_status: "partially_verified",
    tags: "National Museum; Accra; GMMB",
  },
  {
    title: "Ablade Glover — artist and educator",
    record_type: "person",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1934–2024",
    date_start: "1934",
    date_end: "2024",
    creator_or_authority: "Ablade Glover",
    creator_role: "painter; printmaker; educator",
    source_facts:
      "Ablade Glover (1934–2024) was a leading Ghanaian painter and printmaker, professor at KNUST and founder of Artists Alliance Gallery in Accra. Obituaries and gallery records document his influence on modern Ghanaian art markets and pedagogy.",
    ared_interpretation:
      "Glover linked academic training, marketplace display and international collecting — shaping how Ghanaian modern art is visually consumed.",
    primary_source_name: "Artists Alliance Gallery",
    primary_source_url: "https://www.artistsalliancegallery.com/",
    verification_status: "partially_verified",
    tags: "Ablade Glover; painting; KNUST; gallery",
  },
  {
    title: "Atta Kwami — painter, printmaker and colour systems",
    record_type: "person",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V7",
    visual_system_label: "Digital, diasporic and contemporary design",
    date_display: "1956–2021",
    date_start: "1956",
    date_end: "2021",
    creator_or_authority: "Atta Kwami",
    creator_role: "artist; author",
    locality: "Kumasi; UK",
    source_facts:
      "Atta Kwami (1956–2021) was a Ghanaian artist and author of Kumasi Realism and other texts on West African colour and kiosk painting. Tate and international collections document his abstract paintings drawing on Ghanaian architectural colour.",
    ared_interpretation:
      "Kwami theorised Ghanaian popular colour as a designed system — connecting kiosk painting to fine art modernism.",
    primary_source_name: "Tate — Atta Kwami",
    primary_source_url: "https://www.tate.org.uk/art/artists/atta-kwami-26779",
    verification_status: "partially_verified",
    tags: "Atta Kwami; painting; Kumasi Realism; colour",
  },

  // ── State media, currency & public graphics (P4–P6) ───────────────────────
  {
    title: "Ghana Broadcasting Corporation (GBC) television graphics",
    record_type: "institution",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "television from 1965",
    date_start: "1965",
    date_end: "2026",
    institution_or_collection: "Ghana Broadcasting Corporation",
    object_type: "broadcast ident; title card",
    medium: "television graphics",
    source_facts:
      "GBC launched television broadcasting in 1965, producing title cards, news graphics and ceremonial coverage that visualised the young republic for domestic audiences.",
    ared_interpretation:
      "Broadcast graphics extended state visual identity into nightly domestic viewing.",
    primary_source_name: "Ghana Broadcasting Corporation",
    primary_source_url: "https://www.gbcghana.com/",
    verification_status: "source_located",
    tags: "GBC; television; broadcast; state media",
  },
  {
    title: "Ghana cedi banknote design series",
    record_type: "documented practice",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1965–present (successive issues)",
    date_start: "1965",
    date_end: "2026",
    institution_or_collection: "Bank of Ghana",
    object_type: "banknote",
    medium: "intaglio; security print",
    source_facts:
      "Bank of Ghana currency issues from the cedi's introduction in 1965 onward feature portraits of leaders, cocoa industry, castles and cultural motifs. Bank publications document design changes across political eras.",
    ared_interpretation:
      "Banknotes are mass-circulated designed surfaces — state narrative in pocket-sized graphic form.",
    primary_source_name: "Bank of Ghana — currency museum / notes",
    primary_source_url: "https://www.bog.gov.gh/",
    verification_status: "source_located",
    tags: "cedi; currency; Bank of Ghana; banknote",
  },
  {
    title: "Volta River Authority publicity and development graphics",
    record_type: "documented practice",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1960s",
    date_start: "1961",
    date_end: "1980",
    institution_or_collection: "Volta River Authority",
    object_type: "development publicity",
    medium: "poster; brochure; photography",
    source_facts:
      "The Akosombo Dam project was accompanied by publicity presenting electrification and modernisation. VRA and Nkrumah-era materials used photography and bold layout to visualise infrastructural nation-building.",
    ared_interpretation:
      "Development publicity is a designed genre of post-colonial optimism — dams, wires and factories as graphic icons.",
    primary_source_name: "Volta River Authority",
    primary_source_url: "https://www.vra.com/",
    verification_status: "source_located",
    tags: "VRA; Akosombo; development; poster",
  },
  {
    title: "Tema industrial port city advertising",
    record_type: "documented practice",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "1960s–1970s",
    date_start: "1960",
    date_end: "1980",
    locality: "Tema",
    object_type: "industrial advertising",
    medium: "photography; print advertisement",
    source_facts:
      "Tema, Ghana's planned industrial port city, generated corporate and state advertising around oil, shipping and manufacturing. Museum and library holdings include mid-century industrial publicity linked to Tema.",
    ared_interpretation:
      "Tema imagery visualised Ghana's industrial modernity — parallel to Barnor-era commercial photography.",
    primary_source_name: "Cleveland Museum — Tema Ghana industrial photographs (example accession)",
    primary_source_url: "https://clevelandart.org/art/2022.409",
    verification_status: "source_located",
    tags: "Tema; industry; advertising; port",
  },
  {
    title: "Ghana @ 50 independence anniversary branding",
    record_type: "design programme",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "2007",
    date_start: "2007",
    date_end: "2007",
    object_type: "anniversary branding",
    medium: "logo; poster; event graphics",
    source_facts:
      "Ghana marked 50 years of independence in 2007 with public ceremonies, merchandise and commemorative graphics documented in press and philatelic issues.",
    ared_interpretation:
      "Anniversary campaigns recycle independence colour and star motifs for new generational audiences.",
    primary_source_name: "Ghana 50 commemorative materials — press archive",
    primary_source_url: "https://www.ghana.gov.gh/",
    verification_status: "source_located",
    tags: "Ghana 50; anniversary; branding; 2007",
  },
  {
    title: "Electoral Commission ballot and voter education graphics",
    record_type: "documented practice",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1992–present",
    date_start: "1992",
    date_end: "2026",
    institution_or_collection: "Electoral Commission of Ghana",
    object_type: "ballot paper; voter poster",
    medium: "print; infographic",
    source_facts:
      "Since the 1992 return to multi-party elections, Ghana's Electoral Commission has produced ballot layouts and voter education posters designed for literacy and accessibility across diverse electorates.",
    ared_interpretation:
      "Electoral graphics are critical civic design — clarity, symbol and party colour regulated for democratic process.",
    primary_source_name: "Electoral Commission of Ghana",
    primary_source_url: "https://ec.gov.gh/",
    verification_status: "source_located",
    tags: "election; ballot; EC; civic design",
  },

  // ── Contemporary & street culture (P6) ────────────────────────────────────
  {
    title: "Chale Wote Street Art Festival, Jamestown Accra",
    record_type: "event",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V7",
    visual_system_label: "Digital, diasporic and contemporary design",
    date_display: "from 2011",
    date_start: "2011",
    date_end: "2026",
    locality: "Jamestown; Accra",
    object_type: "street art festival",
    medium: "mural; performance; zine",
    source_facts:
      "Chale Wote Street Art Festival began in 2011 in Accra's Jamestown, showcasing murals, performance and independent publishing. Festival archives and press document it as a major platform for contemporary Ghanaian urban graphics.",
    ared_interpretation:
      "Chale Wote reclaimed colonial-era urban space for experimental public graphics and diasporic art networks.",
    primary_source_name: "Chale Wote Street Art Festival",
    primary_source_url: "https://chalewotefest.com/",
    verification_status: "partially_verified",
    tags: "Chale Wote; street art; Jamestown; festival",
  },
  {
    title: "Accra sign-painting and kiosk typography",
    record_type: "documented practice",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V6",
    visual_system_label: "Popular and everyday graphics",
    date_display: "20th–21st century",
    date_start: "1960",
    date_end: "2026",
    locality: "Accra; Kumasi",
    object_type: "hand-painted sign",
    medium: " enamel paint on board",
    source_facts:
      "Hand-painted shop signs, taxi slogans and kiosk lettering remain visible across Ghanaian cities. Atta Kwami and other scholars document Kumasi and Accra lettering styles as distinctive popular typography.",
    ared_interpretation:
      "Street signage is Ghana's most ubiquitous graphic layer — local authorship outside formal design studios.",
    primary_source_name: "Atta Kwami, Kumasi Realism (2013)",
    primary_source_url: "https://www.tate.org.uk/art/artists/atta-kwami-26779",
    verification_status: "source_located",
    tags: "sign painting; typography; kiosk; Accra",
  },
  {
    title: "ATL and Ghana Textile Printing (GTP) local pattern design",
    record_type: "institution",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V3",
    visual_system_label: "Cloth, pattern and social identity",
    date_display: "mid–late 20th century",
    date_start: "1960",
    date_end: "2026",
    institution_or_collection: "Ghana Textile Printing Company",
    object_type: "textile design studio",
    medium: "wax print pattern",
    source_facts:
      "Ghana Textile Printing (GTP) and related firms produced wax cloth patterns named and marketed for Ghanaian consumers, continuing a regional tradition of factory-designed textiles with local semantic naming.",
    ared_interpretation:
      "Local textile mills adapted industrial print to Ghanaian taste — a hybrid designed commodity central to dress culture.",
    primary_source_name: "GTP / ATL corporate histories",
    primary_source_url: "https://www.gtp-fashion.com/",
    verification_status: "source_located",
    tags: "GTP; ATL; wax print; textile industry",
  },
  {
    title: "Pan-Africanist colour and Black Star symbolism in diaspora design",
    record_type: "documented practice",
    period_id: "P6",
    period_label: "Democratic, digital and diasporic design, 1992–present",
    visual_system_id: "V7",
    visual_system_label: "Digital, diasporic and contemporary design",
    date_display: "20th–21st century",
    date_start: "1957",
    date_end: "2026",
    source_facts:
      "Ghana's red-gold-green tricolour and black star recur in diaspora fashion, music branding and political graphics worldwide, extending independence-era symbolism into global Black visual culture.",
    ared_interpretation:
      "Ghanaian state graphics became diasporic design resources — worn, remixed and cited far beyond national borders.",
    primary_source_name: "Government of Ghana — national symbols",
    primary_source_url: "https://www.ghana.gov.gh/about-ghana/national-symbols/",
    verification_status: "partially_verified",
    tags: "diaspora; Black Star; pan-African; symbolism",
  },
  {
    title: "Kwame Nkrumah Mausoleum and Park visual environment",
    record_type: "site",
    period_id: "P5",
    period_label: "Post-independence public and popular graphics, 1966–1992",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "1992 dedication (mausoleum)",
    date_start: "1992",
    date_end: "2026",
    locality: "Accra",
    object_type: "memorial architecture",
    medium: "architecture; relief; landscape",
    source_facts:
      "The Kwame Nkrumah Mausoleum in Accra, designed by Don Arthur and dedicated in 1992, presents Nkrumah's legacy through monumental form, relief and curated exhibition graphics managed under GMMB.",
    ared_interpretation:
      "Memorial sites are designed narrative environments — architecture plus didactic graphics.",
    primary_source_name: "Ghana Museums — Kwame Nkrumah Mausoleum",
    primary_source_url: "https://gmmb.gov.gh/kwame-nkrumah-mausoleum/",
    verification_status: "source_located",
    tags: "Nkrumah Mausoleum; memorial; Accra; architecture",
  },
  {
    title: "Black Star Square (Independence Square) ceremonial graphics",
    record_type: "site",
    period_id: "P4",
    period_label: "Anticolonial and independence visual culture, 1945–1966",
    visual_system_id: "V5",
    visual_system_label: "Independence and state visual identity",
    date_display: "completed 1961",
    date_start: "1961",
    date_end: "2026",
    locality: "Accra",
    object_type: "ceremonial architecture",
    source_facts:
      "Independence Square (Black Star Square) in Accra, completed for Queen Elizabeth II's 1961 visit, hosts independence celebrations with banners, tribunes and televised ceremonial layout documented in state media archives.",
    ared_interpretation:
      "The square is a designed stage for national spectacle — where flags, uniforms and banners compose live graphics.",
    primary_source_name: "Ghana independence architecture histories",
    primary_source_url: "https://www.ghana.gov.gh/about-ghana/national-symbols/",
    verification_status: "source_located",
    tags: "Independence Square; Black Star Square; ceremony; Accra",
  },
];
