"use client";
import { useState } from "react";
import Link from "next/link";
import AredLogo from "@/app/home-next/AredLogo";
import { signInWithPassword, requestPasswordReset } from "./actions";
import AuthSubmit from "@/components/auth/AuthSubmit";
import OAuthButtons from "./OAuthButtons";
export default function LoginForm({next,error,notice}:{next:string;error?:string;notice?:string}) {
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false);
 return <section className="signup-sequence"><div className="signup-progress"><Link href="/home-next" className="signup-back" aria-label="Back to archive"><svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path d="M15 5l-7 7 7 7" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg></Link><Link href="/home-next" aria-label="ARED home"><AredLogo size={30}/></Link><span/></div><div className="signup-stage"><h1>Welcome back</h1><p>Continue your discoveries, or <Link href={`/signup?next=${encodeURIComponent(next)}`}>sign up</Link></p>{error && <p role="alert" className="signup-error">{error}</p>}{notice && <p role="status">{notice}</p>}<form action={signInWithPassword} className="login-fields"><input type="hidden" name="next" value={next}/><label className="signup-input"><span className="ared-sr">Email address</span><input type="email" name="email" autoComplete="email" placeholder="Email address" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="signup-input"><span className="ared-sr">Password</span><input aria-label="Password" type={show?"text":"password"} name="password" autoComplete="current-password" placeholder="Password" required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?"Hide password":"Show password"} onClick={()=>setShow(!show)}>{show?"Hide":"Show"}</button></label><AuthSubmit disabled={!email || !password} pendingLabel="Signing in…">Continue</AuthSubmit></form><details className="auth-recovery"><summary>Forgot password?</summary><form action={requestPasswordReset}><input type="hidden" name="statusPath" value="/signin"/><input type="hidden" name="next" value={next}/><label className="signup-input"><span className="ared-sr">Reset email</span><input type="email" name="email" required autoComplete="email" defaultValue={email} placeholder="Email address"/></label><AuthSubmit pendingLabel="Sending reset link…">Send reset link</AuthSubmit></form></details><div className="auth-divider"><span>or</span></div><OAuthButtons next={next}/></div><Link href="/home-next" className="signup-brand">ARED</Link></section>;
}
