module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/favicon.ico (static in ecmascript, tag client)", ((__turbopack_context__) => {

__turbopack_context__.v("/_next/static/media/favicon.0t86r26w3oqj6.ico" + (globalThis["NEXT_CLIENT_ASSET_SUFFIX"] || ''));}),
"[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$favicon$2e$ico__$28$static__in__ecmascript$2c$__tag__client$29$__ = __turbopack_context__.i("[project]/app/favicon.ico (static in ecmascript, tag client)");
;
const __TURBOPACK__default__export__ = {
    src: __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$favicon$2e$ico__$28$static__in__ecmascript$2c$__tag__client$29$__["default"],
    width: 48,
    height: 48
};
}),
"[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx <module evaluation>", "default");
}),
"[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx", "default");
}),
"[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f28$app$292f$my$2f$workbench$2f$WorkbenchOverviewClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f28$app$292f$my$2f$workbench$2f$WorkbenchOverviewClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f28$app$292f$my$2f$workbench$2f$WorkbenchOverviewClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[externals]/fs/promises [external] (fs/promises, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("fs/promises", () => require("fs/promises"));

module.exports = mod;
}),
"[project]/lib/archive-metadata.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ACCESS_TYPES",
    ()=>ACCESS_TYPES,
    "ADMIN_FILTERS",
    ()=>ADMIN_FILTERS,
    "COMMUNITY_GROUPS",
    ()=>COMMUNITY_GROUPS,
    "COMMUNITY_REVIEW_STATUSES",
    ()=>COMMUNITY_REVIEW_STATUSES,
    "CULTURAL_SENSITIVITIES",
    ()=>CULTURAL_SENSITIVITIES,
    "CURATED_COLLECTIONS",
    ()=>CURATED_COLLECTIONS,
    "KNOWLEDGE_AREAS",
    ()=>KNOWLEDGE_AREAS,
    "LANGUAGES",
    ()=>LANGUAGES,
    "LICENCES",
    ()=>LICENCES,
    "PERIODS",
    ()=>PERIODS,
    "RECORD_TYPES",
    ()=>RECORD_TYPES,
    "REGIONS",
    ()=>REGIONS,
    "REUSE_PERMISSIONS",
    ()=>REUSE_PERMISSIONS,
    "RIGHTS_STATUSES",
    ()=>RIGHTS_STATUSES,
    "SCRIPTS",
    ()=>SCRIPTS,
    "SOURCE_TYPES",
    ()=>SOURCE_TYPES,
    "VERIFICATION_STATUSES",
    ()=>VERIFICATION_STATUSES,
    "canPublishRecord",
    ()=>canPublishRecord,
    "getAdminMetadataIssues",
    ()=>getAdminMetadataIssues,
    "normalizeArchiveRecord",
    ()=>normalizeArchiveRecord,
    "slugifyMetadataTerm",
    ()=>slugifyMetadataTerm
]);
const RECORD_TYPES = [
    "Architecture / Built Work",
    "Archival Document",
    "Artefact",
    "Book",
    "Book Chapter",
    "Exhibition Record",
    "Image",
    "Institutional Record",
    "Journal Article",
    "Manuscript",
    "Oral History",
    "Performance / Sonic Record",
    "Poster",
    "Reference Volume",
    "Teaching Resource",
    "Textile",
    "Website / Digital Resource",
    "Dataset / Metadata Record"
];
const KNOWLEDGE_AREAS = [
    "African Philosophy",
    "Architecture and Space",
    "Craft and Making",
    "Decolonial Theory",
    "Design History",
    "Education and Pedagogy",
    "Environmental Knowledge",
    "Epistemology",
    "Food Systems",
    "Gender and Feminist Thought",
    "Governance and Civic Life",
    "Indigenous Knowledge Systems",
    "Informal Economies",
    "Language and Writing Systems",
    "Material Culture",
    "Music and Performance",
    "Oral Tradition",
    "Political Thought",
    "Spiritual Practice",
    "Textile Knowledge",
    "Visual Culture"
];
const REGIONS = [
    "Africa-wide / Pan-African",
    "North Africa",
    "West Africa",
    "Central Africa",
    "East Africa",
    "Southern Africa",
    "Sahel",
    "African Diaspora",
    "Global / Comparative"
];
const COMMUNITY_GROUPS = [
    "Akan",
    "Asante",
    "Yoruba",
    "Igbo",
    "Hausa",
    "Oromo",
    "Zulu",
    "Xhosa",
    "Ewe",
    "Mande",
    "Tuareg / Amazigh",
    "Swahili Coast Communities",
    "Multiple / Pan-African",
    "Unknown / Needs Review"
];
const LANGUAGES = [
    "English",
    "French",
    "Arabic",
    "Portuguese",
    "Yoruba",
    "Hausa",
    "Swahili",
    "Akan / Twi",
    "Amharic",
    "Other African Language",
    "Multiple Languages",
    "Unknown"
];
const SCRIPTS = [
    "Latin",
    "Arabic",
    "Ajami",
    "Ge'ez",
    "Nsibidi",
    "Tifinagh",
    "N'Ko",
    "Vai",
    "Other",
    "Unknown"
];
const PERIODS = [
    "Precolonial",
    "Colonial",
    "Independence Era",
    "Postcolonial",
    "Contemporary",
    "Unknown / Undated"
];
const CURATED_COLLECTIONS = [
    "African Philosophy Working Library",
    "Decolonial Theory Canon",
    "African Material Culture",
    "Architecture Beyond Colonialism",
    "Manuscripts & Precolonial Texts",
    "West African Oral Traditions",
    "Liberation Movement Graphics"
];
const RIGHTS_STATUSES = [
    "Public Domain",
    "Creative Commons",
    "Open Access",
    "In Copyright",
    "Permission Granted",
    "Metadata Only",
    "Link Only",
    "Rights Unknown",
    "Restricted / Sensitive",
    "Review Required",
    "Check source"
];
const LICENCES = [
    "CC0",
    "CC BY",
    "CC BY 4.0",
    "CC BY-SA",
    "CC BY-NC",
    "CC BY-NC-SA",
    "CC BY-ND",
    "CC BY-NC-ND",
    "Public Domain Mark",
    "RightsStatements.org URI",
    "All Rights Reserved",
    "Check source",
    "Unknown",
    "Custom / Other"
];
const ACCESS_TYPES = [
    "Full Text Available",
    "Download Available",
    "Read Online",
    "Image Available",
    "Thumbnail Only",
    "External Link Only",
    "Metadata Only",
    "Restricted Access",
    "Requires Permission",
    "Community Review Required",
    "Check Source"
];
const REUSE_PERMISSIONS = [
    "Reuse Allowed with Attribution",
    "Non-Commercial Reuse Only",
    "Educational Use Only",
    "No Reuse Without Permission",
    "Check Original Source",
    "Unknown"
];
const CULTURAL_SENSITIVITIES = [
    "Public",
    "Context Required",
    "Sensitive",
    "Community Review Needed",
    "Restricted",
    "Do Not Display Media",
    "Takedown / Review Requested"
];
const COMMUNITY_REVIEW_STATUSES = [
    "Not Required",
    "Not Reviewed",
    "Review Requested",
    "Community Reviewed",
    "Restricted by Community",
    "Do Not Publish"
];
const VERIFICATION_STATUSES = [
    "Verified",
    "Source Checked",
    "Rights Checked",
    "External Source",
    "Metadata Reviewed",
    "AI-Assisted, Needs Review",
    "Community Submitted",
    "Unverified",
    "Provisional",
    "Needs Correction",
    "Duplicate Suspected",
    "Takedown Requested"
];
const SOURCE_TYPES = [
    "Museum / Gallery",
    "Library Catalogue",
    "Archive",
    "Journal Database",
    "University Repository",
    "Book Publisher",
    "Community Submission",
    "Government Source",
    "NGO / Cultural Organisation",
    "Researcher Submitted",
    "Web Resource",
    "AI-Assisted Discovery"
];
const ADMIN_FILTERS = [
    "Rights unclear",
    "Copyright risk",
    "Cultural review required",
    "AI-assisted record",
    "Missing source URL",
    "Missing citation",
    "Missing rights holder",
    "Missing date accessed",
    "Duplicate theme",
    "Needs metadata cleanup",
    "Takedown requested",
    "Missing cultural sensitivity status",
    "Missing verification status"
];
const valueMaps = new Map([
    [
        "african philosophy",
        "African Philosophy"
    ],
    [
        "political thought",
        "Political Thought"
    ],
    [
        "music & performance",
        "Music and Performance"
    ],
    [
        "music and performance",
        "Music and Performance"
    ],
    [
        "oral traditions",
        "Oral Tradition"
    ],
    [
        "oral tradition",
        "Oral Tradition"
    ],
    [
        "indigenous epistemologies",
        "Indigenous Knowledge Systems"
    ],
    [
        "indigenous knowledge systems",
        "Indigenous Knowledge Systems"
    ],
    [
        "language & script",
        "Language and Writing Systems"
    ],
    [
        "language and writing systems",
        "Language and Writing Systems"
    ],
    [
        "design & making",
        "Craft and Making"
    ],
    [
        "material culture",
        "Material Culture"
    ],
    [
        "visual culture",
        "Visual Culture"
    ],
    [
        "decolonial theory",
        "Decolonial Theory"
    ],
    [
        "history & theory",
        "Decolonial Theory"
    ],
    [
        "philosophy & theory",
        "African Philosophy"
    ],
    [
        "architecture",
        "Architecture / Built Work"
    ],
    [
        "architecture / built work",
        "Architecture / Built Work"
    ],
    [
        "books & texts",
        "Book"
    ],
    [
        "oral histories",
        "Oral History"
    ],
    [
        "twi",
        "Akan / Twi"
    ],
    [
        "akan/twi",
        "Akan / Twi"
    ],
    [
        "ge'ez",
        "Ge'ez"
    ],
    [
        "geez",
        "Ge'ez"
    ]
]);
function text(value) {
    return typeof value === "string" ? value.trim() : "";
}
function values(value) {
    if (Array.isArray(value)) return value.map(text).filter(Boolean);
    const single = text(value);
    if (!single) return [];
    return single.split(/\s*(?:,|;|\s\/\s)\s*/g).map((item)=>item.trim()).filter(Boolean);
}
function slugifyMetadataTerm(value) {
    return value.normalize("NFKD").replace(/['’]/g, "").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();
}
function canonical(value) {
    return valueMaps.get(value.trim().toLowerCase()) || value.trim();
}
function uniqueCanonical(items, allowed) {
    const allowedSet = allowed ? new Set(allowed) : null;
    const seen = new Set();
    const next = [];
    values(items).forEach((item)=>{
        const normal = canonical(item);
        if (allowedSet && !allowedSet.has(normal)) return;
        const key = slugifyMetadataTerm(normal);
        if (seen.has(key)) return;
        seen.add(key);
        next.push(normal);
    });
    return next;
}
function normalizeRegion(items) {
    const raw = values(items);
    const expanded = [];
    raw.forEach((item)=>{
        const lower = item.toLowerCase();
        if (lower.includes("west")) expanded.push("West Africa");
        if (lower.includes("north")) expanded.push("North Africa");
        if (lower.includes("east")) expanded.push("East Africa");
        if (lower.includes("southern") || lower.includes("south africa")) expanded.push("Southern Africa");
        if (lower.includes("central")) expanded.push("Central Africa");
        if (lower.includes("sahel")) expanded.push("Sahel");
        if (lower.includes("diaspora")) expanded.push("African Diaspora");
        if (lower.includes("global") || lower.includes("comparative")) expanded.push("Global / Comparative");
        if (lower.includes("pan-africa") || lower.includes("pan africa") || lower.includes("africa / global") || lower.includes("africa-wide")) expanded.push("Africa-wide / Pan-African");
    });
    return uniqueCanonical(expanded.length ? expanded : raw, REGIONS);
}
function normalizeRecordType(record) {
    const raw = uniqueCanonical(record.recordType ?? record.type, RECORD_TYPES);
    if (raw.length) return raw;
    const candidate = canonical(text(record.cat));
    return RECORD_TYPES.includes(candidate) ? [
        candidate
    ] : [
        "Dataset / Metadata Record"
    ];
}
function normalizeKnowledgeAreas(record) {
    const legacyTypeAreas = uniqueCanonical(record.type, KNOWLEDGE_AREAS);
    return uniqueCanonical([
        ...values(record.knowledgeAreas),
        ...values(record.themes),
        ...values(record.concepts),
        ...values(record.tags),
        ...values(record.cat),
        ...legacyTypeAreas
    ], KNOWLEDGE_AREAS);
}
function normalizeLanguageAndScript(record) {
    const rawLanguage = values(record.language);
    const scripts = [
        ...values(record.script)
    ];
    const languages = [];
    rawLanguage.forEach((item)=>{
        if (item.toLowerCase() === "ajami") scripts.push("Ajami");
        else languages.push(item);
    });
    return {
        language: uniqueCanonical(languages.length ? languages : [
            "Unknown"
        ], LANGUAGES),
        script: uniqueCanonical(scripts, SCRIPTS)
    };
}
function normalizeArchiveRecord(input) {
    const record = input && typeof input === "object" ? input : {};
    const now = new Date().toISOString();
    const descriptionParts = values(record.description);
    const summary = text(record.summary) || text(record.abstract);
    const { language, script } = normalizeLanguageAndScript(record);
    const rightsStatus = canonical(text(record.rightsStatus) || text(record.rights) || "Rights Unknown");
    const accessType = canonical(text(record.accessType) || (text(record.sourceUrl) ? "External Link Only" : "Metadata Only"));
    const culturalSensitivity = canonical(text(record.culturalSensitivity) || "Public");
    const verificationStatus = canonical(text(record.verificationStatus) || (record.aiAssisted ? "AI-Assisted, Needs Review" : "Provisional"));
    const sourceName = text(record.sourceName) || text(record.source) || text(record.institution);
    const sourceUrl = text(record.sourceUrl);
    const citation = text(record.citation) || [
        text(record.creator),
        text(record.title),
        sourceName,
        sourceUrl
    ].filter(Boolean).join(". ");
    const normalized = {
        id: text(record.id) || `record-${Date.now()}`,
        title: text(record.title) || "Untitled record",
        alternativeTitles: uniqueCanonical(record.alternativeTitles ?? record.alternateTitle),
        description: descriptionParts.join("\n\n") || summary || text(record.title) || "Description pending metadata review.",
        creator: text(record.creator),
        contributors: uniqueCanonical(record.contributors),
        publisher: text(record.publisher),
        recordType: normalizeRecordType(record),
        knowledgeAreas: normalizeKnowledgeAreas(record),
        curatedCollections: uniqueCanonical(record.curatedCollections ?? record.collection, CURATED_COLLECTIONS),
        region: normalizeRegion(record.region),
        country: uniqueCanonical(record.country ?? record.countries),
        place: uniqueCanonical(record.place),
        communityOrCulturalGroup: uniqueCanonical(record.communityOrCulturalGroup ?? record.community),
        language,
        script,
        dateCreated: text(record.dateCreated),
        datePublished: text(record.datePublished),
        dateDigitised: text(record.dateDigitised),
        dateAccessed: text(record.dateAccessed),
        period: uniqueCanonical(record.period, PERIODS),
        sourceName,
        sourceUrl,
        citation,
        identifier: text(record.identifier) || text(record.recordIdentifier),
        doi: text(record.doi),
        isbn: text(record.isbn),
        rightsStatus: RIGHTS_STATUSES.includes(rightsStatus) ? rightsStatus : "Rights Unknown",
        licence: text(record.licence),
        rightsStatementUri: text(record.rightsStatementUri),
        rightsHolder: text(record.rightsHolder),
        accessType: ACCESS_TYPES.includes(accessType) ? accessType : "Metadata Only",
        reusePermission: text(record.reusePermission) || "Check Original Source",
        recommendedAttribution: text(record.recommendedAttribution),
        copyrightNote: text(record.copyrightNote),
        permissionEvidence: text(record.permissionEvidence),
        culturalSensitivity: CULTURAL_SENSITIVITIES.includes(culturalSensitivity) ? culturalSensitivity : "Public",
        traditionalOwnersOrKnowledgeHolders: text(record.traditionalOwnersOrKnowledgeHolders),
        culturalProtocolNote: text(record.culturalProtocolNote),
        colonialLanguageWarning: Boolean(record.colonialLanguageWarning),
        reparativeDescriptionNote: text(record.reparativeDescriptionNote),
        localContextsLabel: text(record.localContextsLabel),
        localContextsNotice: text(record.localContextsNotice),
        communityReviewStatus: text(record.communityReviewStatus) || "Not Required",
        verificationStatus: VERIFICATION_STATUSES.includes(verificationStatus) ? verificationStatus : "Provisional",
        sourceType: text(record.sourceType),
        sourceChecked: Boolean(record.sourceChecked),
        rightsChecked: Boolean(record.rightsChecked),
        metadataReviewed: Boolean(record.metadataReviewed),
        aiAssisted: Boolean(record.aiAssisted),
        confidenceLevel: record.confidenceLevel === "high" || record.confidenceLevel === "medium" || record.confidenceLevel === "low" ? record.confidenceLevel : undefined,
        adminNotes: text(record.adminNotes),
        published: Boolean(record.published),
        status: text(record.status) || (record.published ? "Published" : "Draft"),
        summary,
        tags: uniqueCanonical(record.tags),
        notes: values(record.notes),
        type: normalizeRecordType(record)[0],
        source: sourceName,
        institution: text(record.institution),
        collection: uniqueCanonical(record.curatedCollections ?? record.collection, CURATED_COLLECTIONS)[0],
        sourceActionLabel: text(record.sourceActionLabel),
        archiveIdentifier: text(record.archiveIdentifier),
        recordIdentifier: text(record.recordIdentifier) || text(record.identifier),
        abstract: text(record.abstract),
        keywords: uniqueCanonical(record.keywords),
        createdAt: text(record.createdAt) || now,
        updatedAt: now
    };
    if (!normalized.dateAccessed) normalized.dateAccessed = "";
    if (!normalized.region.length && !normalized.country?.length) normalized.region = [];
    if (!normalized.knowledgeAreas.length) normalized.knowledgeAreas = [
        "Decolonial Theory"
    ];
    normalized.published = canPublishRecord(normalized).ok && normalized.status === "Published";
    if (!normalized.published && normalized.status === "Published") normalized.status = "Needs Review";
    return normalized;
}
function canPublishRecord(record) {
    const missing = [];
    const requireText = (label, value)=>{
        if (!text(value)) missing.push(label);
    };
    const requireList = (label, value)=>{
        if (!values(value).length) missing.push(label);
    };
    requireText("Title", record.title);
    requireList("Record Type", record.recordType);
    requireText("Description", record.description);
    requireText("Source Name", record.sourceName);
    requireText("Source URL", record.sourceUrl);
    requireText("Citation", record.citation);
    if (!record.region.length && !record.country?.length) missing.push("Region or Country");
    requireList("Knowledge Area", record.knowledgeAreas);
    requireList("Language", record.language);
    requireText("Rights Status", record.rightsStatus);
    requireText("Access Type", record.accessType);
    requireText("Verification Status", record.verificationStatus);
    requireText("Date Accessed", record.dateAccessed);
    const communityKnowledge = record.culturalSensitivity !== "Public" || Boolean(record.traditionalOwnersOrKnowledgeHolders) || Boolean(record.localContextsLabel) || Boolean(record.localContextsNotice);
    if (communityKnowledge) {
        requireText("Cultural Sensitivity", record.culturalSensitivity);
        requireList("Community / Cultural Group", record.communityOrCulturalGroup);
        requireText("Cultural Protocol Note", record.culturalProtocolNote);
        requireText("Community Review Status", record.communityReviewStatus);
    }
    return {
        ok: missing.length === 0,
        missing
    };
}
function getAdminMetadataIssues(record) {
    const issues = [];
    if (!record.rightsStatus) issues.push("Missing rights status");
    if (!record.sourceUrl) issues.push("Missing source URL");
    if (!record.citation) issues.push("Missing citation");
    if (record.rightsStatus === "Rights Unknown") issues.push("Rights unknown");
    if (record.rightsStatus === "In Copyright" || record.rightsStatus === "Restricted / Sensitive") issues.push("Copyright risk");
    if (record.culturalSensitivity === "Community Review Needed") issues.push("Cultural review needed");
    if (record.aiAssisted || record.verificationStatus === "AI-Assisted, Needs Review") issues.push("AI-assisted record");
    if (record.verificationStatus === "Provisional") issues.push("Provisional");
    if (!record.language.length) issues.push("Missing language");
    if (!record.dateAccessed) issues.push("Missing date accessed");
    if (!record.rightsHolder) issues.push("Missing rights holder");
    if (!record.culturalSensitivity) issues.push("Missing cultural sensitivity status");
    if (!record.verificationStatus) issues.push("Missing verification status");
    if (record.verificationStatus === "Takedown Requested" || record.culturalSensitivity === "Takedown / Review Requested") {
        issues.push("Takedown requested");
    }
    return issues;
}
}),
"[project]/lib/records.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "readRecords",
    ()=>readRecords,
    "writeRecords",
    ()=>writeRecords
]);
var __TURBOPACK__imported__module__$5b$externals$5d2f$fs$2f$promises__$5b$external$5d$__$28$fs$2f$promises$2c$__cjs$29$__ = __turbopack_context__.i("[externals]/fs/promises [external] (fs/promises, cjs)");
var __TURBOPACK__imported__module__$5b$externals$5d2f$path__$5b$external$5d$__$28$path$2c$__cjs$29$__ = __turbopack_context__.i("[externals]/path [external] (path, cjs)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$archive$2d$metadata$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/archive-metadata.ts [app-rsc] (ecmascript)");
;
;
;
const filePath = __TURBOPACK__imported__module__$5b$externals$5d2f$path__$5b$external$5d$__$28$path$2c$__cjs$29$__["default"].join(process.cwd(), 'data', 'records.json');
const defaultRecords = [];
async function readRecords() {
    try {
        const raw = await __TURBOPACK__imported__module__$5b$externals$5d2f$fs$2f$promises__$5b$external$5d$__$28$fs$2f$promises$2c$__cjs$29$__["default"].readFile(filePath, 'utf-8');
        return JSON.parse(raw).map(__TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$archive$2d$metadata$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeArchiveRecord"]);
    } catch  {
        return defaultRecords;
    }
}
async function writeRecords(records) {
    await __TURBOPACK__imported__module__$5b$externals$5d2f$fs$2f$promises__$5b$external$5d$__$28$fs$2f$promises$2c$__cjs$29$__["default"].mkdir(__TURBOPACK__imported__module__$5b$externals$5d2f$path__$5b$external$5d$__$28$path$2c$__cjs$29$__["default"].dirname(filePath), {
        recursive: true
    });
    await __TURBOPACK__imported__module__$5b$externals$5d2f$fs$2f$promises__$5b$external$5d$__$28$fs$2f$promises$2c$__cjs$29$__["default"].writeFile(filePath, JSON.stringify(records.map(__TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$archive$2d$metadata$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeArchiveRecord"]), null, 2), 'utf-8');
}
}),
"[project]/lib/workbench-data.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "boardColumnForRecordStatus",
    ()=>boardColumnForRecordStatus,
    "getWorkbenchOverviewContext",
    ()=>getWorkbenchOverviewContext,
    "getWorkbenchProjectBundle",
    ()=>getWorkbenchProjectBundle,
    "insertDefaultResearchMilestones",
    ()=>insertDefaultResearchMilestones,
    "listAllWorkbenchAnnotations",
    ()=>listAllWorkbenchAnnotations,
    "listAllWorkbenchCollaborators",
    ()=>listAllWorkbenchCollaborators,
    "listAllWorkbenchProjectRecords",
    ()=>listAllWorkbenchProjectRecords,
    "listAllWorkbenchTasks",
    ()=>listAllWorkbenchTasks,
    "listWorkbenchProjects",
    ()=>listWorkbenchProjects,
    "listWorkbenchProjectsSummary",
    ()=>listWorkbenchProjectsSummary,
    "recordNeedsMetadataReview",
    ()=>recordNeedsMetadataReview,
    "snapshotRecordRights",
    ()=>snapshotRecordRights
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$records$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/records.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$types$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/workbench-types.ts [app-rsc] (ecmascript)");
;
;
;
function addDays(isoDate, days) {
    const d = new Date(isoDate);
    d.setDate(d.getDate() + days);
    return d.toISOString().slice(0, 10);
}
async function listWorkbenchProjects() {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data, error } = await supabase.from("workbench_projects").select("*").order("updated_at", {
        ascending: false
    });
    if (error) return {
        ok: false,
        error: error.message,
        projects: []
    };
    return {
        ok: true,
        projects: data ?? []
    };
}
async function listWorkbenchProjectsSummary() {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data: projects, error } = await supabase.from("workbench_projects").select("*").order("updated_at", {
        ascending: false
    });
    if (error) return {
        ok: false,
        error: error.message,
        projects: []
    };
    const rows = projects ?? [];
    if (!rows.length) return {
        ok: true,
        projects: []
    };
    const ids = rows.map((p)=>p.id);
    const { data: counts, error: countError } = await supabase.from("workbench_project_records").select("project_id").in("project_id", ids);
    if (countError) return {
        ok: false,
        error: countError.message,
        projects: []
    };
    const tally = new Map();
    for (const row of counts ?? []){
        const pid = row.project_id;
        tally.set(pid, (tally.get(pid) ?? 0) + 1);
    }
    return {
        ok: true,
        projects: rows.map((p)=>({
                ...p,
                record_count: tally.get(p.id) ?? 0
            }))
    };
}
async function getWorkbenchProjectBundle(projectId) {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data: project, error: projectError } = await supabase.from("workbench_projects").select("*").eq("id", projectId).maybeSingle();
    if (projectError) {
        return {
            ok: false,
            error: projectError.message,
            project: null,
            records: [],
            tasks: [],
            milestones: [],
            annotations: [],
            collaborators: []
        };
    }
    if (!project) {
        return {
            ok: true,
            project: null,
            records: [],
            tasks: [],
            milestones: [],
            annotations: [],
            collaborators: []
        };
    }
    const [recordsRes, tasksRes, milestonesRes, annotationsRes, collabRes] = await Promise.all([
        supabase.from("workbench_project_records").select("*").eq("project_id", projectId).order("updated_at", {
            ascending: false
        }),
        supabase.from("workbench_tasks").select("*").eq("project_id", projectId).order("due_date", {
            ascending: true
        }),
        supabase.from("workbench_milestones").select("*").eq("project_id", projectId).order("due_date", {
            ascending: true
        }),
        supabase.from("workbench_annotations").select("*").eq("project_id", projectId).order("created_at", {
            ascending: false
        }),
        supabase.from("workbench_collaborators").select("*").eq("project_id", projectId).order("created_at", {
            ascending: true
        })
    ]);
    const firstErr = recordsRes.error || tasksRes.error || milestonesRes.error || annotationsRes.error || collabRes.error;
    if (firstErr) {
        return {
            ok: false,
            error: firstErr.message,
            project: project,
            records: [],
            tasks: [],
            milestones: [],
            annotations: [],
            collaborators: []
        };
    }
    return {
        ok: true,
        project: project,
        records: recordsRes.data ?? [],
        tasks: tasksRes.data ?? [],
        milestones: milestonesRes.data ?? [],
        annotations: annotationsRes.data ?? [],
        collaborators: collabRes.data ?? []
    };
}
async function listAllWorkbenchTasks(limit = 80) {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data: tasks, error } = await supabase.from("workbench_tasks").select("*").order("due_date", {
        ascending: true
    }).limit(limit);
    if (error) return {
        ok: false,
        error: error.message,
        tasks: []
    };
    const taskRows = tasks ?? [];
    const projectIds = Array.from(new Set(taskRows.map((t)=>t.project_id)));
    let titles = new Map();
    if (projectIds.length) {
        const { data: projects } = await supabase.from("workbench_projects").select("id, title").in("id", projectIds);
        titles = new Map((projects ?? []).map((p)=>[
                p.id,
                p.title
            ]));
    }
    return {
        ok: true,
        tasks: taskRows.map((t)=>({
                ...t,
                project_title: titles.get(t.project_id) ?? "Project"
            }))
    };
}
async function listAllWorkbenchAnnotations(limit = 60) {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data, error } = await supabase.from("workbench_annotations").select("*").order("created_at", {
        ascending: false
    }).limit(limit);
    if (error) return {
        ok: false,
        error: error.message,
        annotations: []
    };
    const records = (await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$records$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["readRecords"])()).filter((r)=>r.published);
    const recordsById = new Map(records.map((r)=>[
            r.id,
            r
        ]));
    const annRows = data ?? [];
    const projectIds = Array.from(new Set(annRows.map((a)=>a.project_id)));
    let titles = new Map();
    if (projectIds.length) {
        const { data: projects } = await supabase.from("workbench_projects").select("id, title").in("id", projectIds);
        titles = new Map((projects ?? []).map((p)=>[
                p.id,
                p.title
            ]));
    }
    const annotations = annRows.map((r)=>{
        const rec = recordsById.get(r.record_id);
        return {
            ...r,
            project_title: titles.get(r.project_id) ?? "Project",
            record_title: rec?.title ?? r.record_id
        };
    });
    return {
        ok: true,
        annotations
    };
}
async function listAllWorkbenchProjectRecords(limit = 200) {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data, error } = await supabase.from("workbench_project_records").select("*").order("updated_at", {
        ascending: false
    }).limit(limit);
    if (error) return {
        ok: false,
        error: error.message,
        records: []
    };
    return {
        ok: true,
        records: data ?? []
    };
}
async function listAllWorkbenchCollaborators(limit = 200) {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data, error } = await supabase.from("workbench_collaborators").select("*").order("created_at", {
        ascending: false
    }).limit(limit);
    if (error) return {
        ok: false,
        error: error.message,
        collaborators: []
    };
    return {
        ok: true,
        collaborators: data ?? []
    };
}
async function getWorkbenchOverviewContext() {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const today = new Date().toISOString().slice(0, 10);
    const horizon = addDays(today, 21);
    const { data: projects, error: pErr } = await supabase.from("workbench_projects").select("*").eq("status", "active").order("deadline", {
        ascending: true
    });
    if (pErr) {
        return {
            ok: false,
            error: pErr.message,
            projects: [],
            tasksDueSoon: [],
            recordsNeedingReview: [],
            recentAnnotations: [],
            upcomingDeadlines: []
        };
    }
    const projectRows = projects ?? [];
    const ids = projectRows.map((p)=>p.id);
    const upcomingDeadlines = projectRows.filter((p)=>p.deadline && p.deadline >= today && p.deadline <= horizon).map((p)=>({
            id: p.id,
            title: p.title,
            deadline: p.deadline
        }));
    const { data: tasksRaw, error: tErr } = ids.length ? await supabase.from("workbench_tasks").select("*").in("project_id", ids).neq("status", "done").not("due_date", "is", null).lte("due_date", horizon).order("due_date", {
        ascending: true
    }).limit(40) : {
        data: [],
        error: null
    };
    if (tErr) {
        return {
            ok: false,
            error: tErr.message,
            projects: projectRows,
            tasksDueSoon: [],
            recordsNeedingReview: [],
            recentAnnotations: [],
            upcomingDeadlines
        };
    }
    const taskList = tasksRaw ?? [];
    const taskProjectIds = Array.from(new Set(taskList.map((t)=>t.project_id)));
    let taskTitles = new Map();
    if (taskProjectIds.length) {
        const { data: tp } = await supabase.from("workbench_projects").select("id, title").in("id", taskProjectIds);
        taskTitles = new Map((tp ?? []).map((p)=>[
                p.id,
                p.title
            ]));
    }
    const tasksDueSoon = taskList.map((t)=>({
            ...t,
            project_title: taskTitles.get(t.project_id) ?? "Project"
        }));
    const { data: reviewRecords, error: rErr } = ids.length ? await supabase.from("workbench_project_records").select("*").in("project_id", ids).or("metadata_review_needed.eq.true,cultural_review_needed.eq.true,rights_checked.eq.false,citation_checked.eq.false,source_checked.eq.false").limit(50) : {
        data: [],
        error: null
    };
    if (rErr) {
        return {
            ok: false,
            error: rErr.message,
            projects: projectRows,
            tasksDueSoon,
            recordsNeedingReview: [],
            recentAnnotations: [],
            upcomingDeadlines
        };
    }
    const ann = await listAllWorkbenchAnnotations(12);
    return {
        ok: true,
        projects: projectRows,
        tasksDueSoon,
        recordsNeedingReview: reviewRecords ?? [],
        recentAnnotations: ann.ok ? ann.annotations : [],
        upcomingDeadlines
    };
}
function insertDefaultResearchMilestones(projectId) {
    return __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$types$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DEFAULT_RESEARCH_MILESTONES"].map((title)=>({
            project_id: projectId,
            title,
            description: null,
            due_date: null,
            status: "pending"
        }));
}
function snapshotRecordRights(record) {
    if (!record) {
        return {
            rightsStatus: "",
            licence: "",
            accessType: "",
            verificationStatus: "",
            culturalSensitivity: "",
            communityReviewStatus: "",
            sourceUrl: "",
            dateAccessed: "",
            citation: ""
        };
    }
    return {
        rightsStatus: record.rightsStatus ?? "",
        licence: record.licence ?? "",
        accessType: record.accessType ?? "",
        verificationStatus: record.verificationStatus ?? "",
        culturalSensitivity: record.culturalSensitivity ?? "",
        communityReviewStatus: record.communityReviewStatus ?? "",
        sourceUrl: record.sourceUrl ?? "",
        dateAccessed: record.dateAccessed ?? "",
        citation: record.citation ?? ""
    };
}
function recordNeedsMetadataReview(snapshot) {
    if (!snapshot.citation.trim()) return true;
    if (!snapshot.rightsStatus.trim() || snapshot.rightsStatus === "Rights Unknown") return true;
    if (!snapshot.sourceUrl.trim()) return true;
    if (!snapshot.dateAccessed.trim()) return true;
    if (!snapshot.accessType.trim()) return true;
    if (!snapshot.verificationStatus.trim()) return true;
    return false;
}
function boardColumnForRecordStatus(status) {
    const readingAligned = [
        "to_review",
        "reading",
        "metadata_check",
        "rights_check",
        "cultural_review",
        "writing_annotation",
        "ready_to_publish",
        "completed"
    ];
    if (status === "to_annotate") return "writing_annotation";
    if (status === "exclude") return null;
    if (readingAligned.includes(status)) {
        return status;
    }
    return "to_review";
}
}),
"[project]/src/lib/member-workspace.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "formatWorkspaceDate",
    ()=>formatWorkspaceDate,
    "getMemberWorkspaceData",
    ()=>getMemberWorkspaceData,
    "workspaceRecordTitle",
    ()=>workspaceRecordTitle
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/auth.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$records$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/records.ts [app-rsc] (ecmascript)");
;
;
;
function formatWorkspaceDate(value) {
    return new Intl.DateTimeFormat("en-AU", {
        dateStyle: "medium"
    }).format(new Date(value));
}
function workspaceRecordTitle(recordsById, recordId) {
    const record = recordsById.get(recordId);
    const metadata = asRecord(record?.metadata);
    const data = asRecord(record?.data);
    const raw = asRecord(record?.raw);
    return firstWorkspaceText(record?.title, record?.name, record?.label, record?.display_title, record?.displayTitle, record?.record_title, record?.recordTitle, record?.source_title, record?.sourceTitle, metadata.title, metadata.display_name, metadata.displayTitle, metadata.display_title, metadata.work_title, metadata.workTitle, data.title, data.display_name, data.displayTitle, data.display_title, raw.title, raw.display_name, raw.displayTitle, raw.display_title) || readableRecordIdFallback(recordId);
}
function readableRecordIdFallback(recordId) {
    const cleaned = recordId.replace(/^live-openalex-https-openalex-org-/i, "OpenAlex ").replace(/^live-/i, "").replace(/-/g, " ").trim();
    return cleaned ? `Untitled record (${cleaned})` : "Untitled record";
}
function asRecord(value) {
    if (!value || typeof value !== "object" || Array.isArray(value)) return {};
    return value;
}
function firstWorkspaceText(...values) {
    for (const value of values){
        if (typeof value === "string" && value.trim()) return value.trim();
        if (typeof value === "number") return String(value);
    }
    return "";
}
async function getMemberWorkspaceData(next = "/workspace") {
    const profile = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["requireMember"])(next);
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const records = (await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$records$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["readRecords"])()).filter((record)=>record.published);
    const recordsById = new Map(records.map((record)=>[
            record.id,
            record
        ]));
    const [bookmarksResult, savedSearchesResult, readingListsResult] = await Promise.all([
        supabase.from("bookmarks").select("id, record_id, record_title, record_source, record_source_url, record_type, record_year, record_metadata, note, created_at").eq("user_id", profile.id).order("created_at", {
            ascending: false
        }),
        supabase.from("saved_searches").select("id, label, query, created_at").eq("user_id", profile.id).order("created_at", {
            ascending: false
        }),
        supabase.from("reading_lists").select("id, title, description, is_public, created_at").eq("user_id", profile.id).order("created_at", {
            ascending: false
        })
    ]);
    const readingLists = readingListsResult.data ?? [];
    const listIds = readingLists.map((list)=>list.id);
    const readingListItemsResult = listIds.length ? await supabase.from("reading_list_items").select("id, reading_list_id, record_id, record_title, record_author, record_source, record_source_url, record_type, record_year, record_metadata, note, added_at").in("reading_list_id", listIds).order("added_at", {
        ascending: false
    }) : {
        data: [],
        error: null
    };
    if (bookmarksResult.error) throw new Error(bookmarksResult.error.message);
    if (savedSearchesResult.error) throw new Error(savedSearchesResult.error.message);
    if (readingListsResult.error) throw new Error(readingListsResult.error.message);
    if (readingListItemsResult.error) {
        throw new Error(readingListItemsResult.error.message);
    }
    return {
        profile,
        records,
        recordsById,
        bookmarks: bookmarksResult.data ?? [],
        savedSearches: savedSearchesResult.data ?? [],
        readingLists,
        readingListItems: readingListItemsResult.data ?? []
    };
}
}),
"[project]/app/(app)/my/workbench/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>WorkbenchOverviewPage
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f28$app$292f$my$2f$workbench$2f$WorkbenchOverviewClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/app/(app)/my/workbench/WorkbenchOverviewClient.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/workbench-data.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/member-workspace.ts [app-rsc] (ecmascript)");
;
;
;
;
function addRecordOption(map, id, title) {
    if (!id || map.has(id)) return;
    map.set(id, {
        id,
        title: title || id
    });
}
async function WorkbenchOverviewPage({ searchParams }) {
    const sp = await searchParams;
    const [overview, projectsRes, tasksRes, projectRecordsRes, annotationsRes, collaboratorsRes, workspace] = await Promise.all([
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getWorkbenchOverviewContext"])(),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listWorkbenchProjects"])(),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listAllWorkbenchTasks"])(300),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listAllWorkbenchProjectRecords"])(300),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listAllWorkbenchAnnotations"])(200),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$workbench$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listAllWorkbenchCollaborators"])(200),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getMemberWorkspaceData"])("/my/workbench")
    ]);
    const errors = [
        sp.error,
        !overview.ok ? overview.error : "",
        !projectsRes.ok ? projectsRes.error : "",
        !tasksRes.ok ? tasksRes.error : "",
        !projectRecordsRes.ok ? projectRecordsRes.error : "",
        !annotationsRes.ok ? annotationsRes.error : "",
        !collaboratorsRes.ok ? collaboratorsRes.error : ""
    ].filter(Boolean);
    const recordOptionMap = new Map();
    workspace.records.slice(0, 300).forEach((record)=>{
        addRecordOption(recordOptionMap, record.id, (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["workspaceRecordTitle"])(workspace.recordsById, record.id));
    });
    workspace.bookmarks.forEach((bookmark)=>{
        addRecordOption(recordOptionMap, bookmark.record_id, bookmark.record_title || (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["workspaceRecordTitle"])(workspace.recordsById, bookmark.record_id));
    });
    workspace.readingListItems.forEach((item)=>{
        addRecordOption(recordOptionMap, item.record_id, item.record_title || (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["workspaceRecordTitle"])(workspace.recordsById, item.record_id));
    });
    if (tasksRes.ok) {
        tasksRes.tasks.forEach((task)=>{
            task.linked_record_ids?.forEach((id)=>{
                addRecordOption(recordOptionMap, id, (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["workspaceRecordTitle"])(workspace.recordsById, id));
            });
        });
    }
    if (projectRecordsRes.ok) {
        projectRecordsRes.records.forEach((record)=>{
            addRecordOption(recordOptionMap, record.record_id, (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$member$2d$workspace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["workspaceRecordTitle"])(workspace.recordsById, record.record_id));
        });
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f28$app$292f$my$2f$workbench$2f$WorkbenchOverviewClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
        projects: projectsRes.ok ? projectsRes.projects : [],
        tasks: tasksRes.ok ? tasksRes.tasks : [],
        projectRecords: projectRecordsRes.ok ? projectRecordsRes.records : [],
        annotations: annotationsRes.ok ? annotationsRes.annotations : [],
        collaborators: collaboratorsRes.ok ? collaboratorsRes.collaborators : [],
        recordOptions: Array.from(recordOptionMap.values()),
        savedRecordsCount: workspace.bookmarks.length,
        readingListsCount: workspace.readingLists.length,
        initialNotice: sp.updated,
        initialError: errors.join(" ")
    }, void 0, false, {
        fileName: "[project]/app/(app)/my/workbench/page.tsx",
        lineNumber: 82,
        columnNumber: 5
    }, this);
}
}),
"[project]/app/(app)/my/workbench/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/(app)/my/workbench/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__0k1l3cl._.js.map