export type SourceType =
  | "open_access_books"
  | "open_textbook"
  | "oer"
  | "institutional_press"
  | "public_domain"
  | "australian_open_collection"
  | "source_handoff";

export type IntegrationMode =
  | "rest_api"
  | "metadata_feed"
  | "oai_pmh"
  | "rdf_catalog"
  | "csv_feed"
  | "rss_atom"
  | "search_handoff"
  | "manual_review";

export type MetadataConfidence = "high" | "medium" | "low";

export type OpenAccessSource = {
  id: string;
  label: string;
  description: string;
  baseUrl: string;
  searchUrlTemplate?: string;
  sourceType: SourceType;
  region: string;
  country: string;
  accessDefault: string;
  rightsDefault: string;
  rightsCaution?: string;
  metadataConfidence: MetadataConfidence;
  integrationMode: IntegrationMode;
  futureHarvestMode?: string;
  metadataLicence?: string;
  requiresApiKey: boolean;
  enabled: boolean;
  canLiveSearch: boolean;
  canHarvest: boolean;
  notes?: string;
};

/**
 * Canonical registry for open-access and related discovery sources.
 * DOAB is the only live REST search in v1; others are handoffs unless extended later.
 */
export const OPEN_ACCESS_SOURCES: OpenAccessSource[] = [
  {
    id: "doab",
    label: "Directory of Open Access Books",
    description:
      "Community-driven discovery service for peer-reviewed open access books. Metadata is CC0; each title carries its own reuse licence.",
    baseUrl: "https://directory.doabooks.org",
    searchUrlTemplate:
      "https://directory.doabooks.org/rest/search?query={{query}}&expand=metadata,bitstreams",
    sourceType: "open_access_books",
    region: "global",
    country: "international",
    accessDefault: "Free online",
    rightsDefault: "Open access, record-level licence supplied where available",
    rightsCaution:
      "DOAB metadata is CC0, but book reuse rights must come from each item’s record-level licence. Do not mark all books as Creative Commons.",
    metadataConfidence: "high",
    integrationMode: "rest_api",
    futureHarvestMode: "oai_pmh",
    metadataLicence: "CC0 1.0",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: true,
    canHarvest: true,
    notes:
      "OAI-PMH: https://directory.doabooks.org/oai/ — harvest-ready for future sync jobs.",
  },
  {
    id: "intech_open",
    label: "InTechOpen Open Access Books",
    description: "STEM and applied sciences open access books from InTechOpen.",
    baseUrl: "https://www.intechopen.com",
    searchUrlTemplate: "https://www.intechopen.com/search?query={{query}}",
    sourceType: "open_access_books",
    region: "global",
    country: "international",
    accessDefault: "Free online",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    futureHarvestMode: "rss_atom",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "jstor_open_ebooks",
    label: "JSTOR open access eBooks",
    description: "JSTOR-hosted open access eBooks discovery (metadata-led handoff).",
    baseUrl: "https://www.jstor.org",
    searchUrlTemplate: "https://www.jstor.org/open/search?Query={{query}}",
    sourceType: "open_access_books",
    region: "global",
    country: "international",
    accessDefault: "Free online where OA",
    rightsDefault: "Check record-level rights on JSTOR",
    rightsCaution: "OA subset; verify licence per title.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "open_book_publishers",
    label: "Open Book Publishers",
    description: "UK-based scholar-led open access book publisher.",
    baseUrl: "https://www.openbookpublishers.com",
    searchUrlTemplate:
      "https://www.openbookpublishers.com/section/14/1/catalogsearch/result/?q={{query}}",
    sourceType: "open_access_books",
    region: "global",
    country: "United Kingdom",
    accessDefault: "Free online",
    rightsDefault: "Open access, record-level licence required",
    rightsCaution: "Display exact record-level licence; do not infer CC.",
    metadataConfidence: "high",
    integrationMode: "search_handoff",
    futureHarvestMode: "metadata_feed",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "project_gutenberg",
    label: "Project Gutenberg",
    description: "Digitised public domain and permission-based literature (US-centric framing).",
    baseUrl: "https://www.gutenberg.org",
    searchUrlTemplate: "https://www.gutenberg.org/ebooks/search/?query={{query}}",
    sourceType: "public_domain",
    region: "global",
    country: "United States",
    accessDefault: "Free online",
    rightsDefault: "Public domain or permission-based, jurisdiction check required",
    rightsCaution:
      "Copyright status may differ outside the United States. Do not mark as globally public domain.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    futureHarvestMode: "rdf_catalog",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "public_domain_review_books",
    label: "Public Domain Review — Books",
    description: "Curated essays and collections highlighting public domain works.",
    baseUrl: "https://publicdomainreview.org",
    searchUrlTemplate: "https://publicdomainreview.org/?s={{query}}",
    sourceType: "public_domain",
    region: "global",
    country: "international",
    accessDefault: "Free online",
    rightsDefault: "Public domain or rights statement varies by item",
    rightsCaution: "Confirm item-level rights and jurisdiction before reuse.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "bc_open_collection",
    label: "B.C. Open Collection",
    description: "British Columbia open educational resources collection.",
    baseUrl: "https://open.bccampus.ca",
    searchUrlTemplate: "https://open.bccampus.ca/browse/?search={{query}}",
    sourceType: "oer",
    region: "north_america",
    country: "Canada",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless explicitly stated.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    futureHarvestMode: "metadata_feed",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "libretexts",
    label: "LibreTexts",
    description: "Multi-discipline OER library network.",
    baseUrl: "https://libretexts.org",
    searchUrlTemplate: "https://search.libretexts.org/?q={{query}}",
    sourceType: "oer",
    region: "global",
    country: "United States",
    accessDefault: "Free online",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Campus-specific instances; verify licence on the landing page.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "openstax",
    label: "OpenStax",
    description: "Rice University–hosted open textbooks.",
    baseUrl: "https://openstax.org",
    searchUrlTemplate: "https://openstax.org/search?q={{query}}",
    sourceType: "open_textbook",
    region: "global",
    country: "United States",
    accessDefault: "Free online / download",
    rightsDefault: "Creative Commons licence supplied per record",
    rightsCaution: "Only show CC labels when the OpenStax record explicitly names the licence.",
    metadataConfidence: "high",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "open_suny_textbooks",
    label: "Open SUNY Textbooks",
    description: "SUNY open textbook catalogue.",
    baseUrl: "https://textbooks.opensuny.org",
    searchUrlTemplate: "https://textbooks.opensuny.org/?s={{query}}",
    sourceType: "open_textbook",
    region: "north_america",
    country: "United States",
    accessDefault: "Free online",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "open_textbook_library",
    label: "Open Textbook Library",
    description: "University of Minnesota–hosted open textbook discovery.",
    baseUrl: "https://open.umn.edu",
    searchUrlTemplate: "https://open.umn.edu/opentextbooks/textbooks?search={{query}}",
    sourceType: "open_textbook",
    region: "global",
    country: "United States",
    accessDefault: "Free online / download",
    rightsDefault: "Creative Commons licence supplied per record",
    rightsCaution: "Display exact record-level licence.",
    metadataConfidence: "high",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "pressbooks_directory",
    label: "Pressbooks Directory",
    description: "Directory of public books hosted on Pressbooks networks.",
    baseUrl: "https://pressbooks.directory",
    searchUrlTemplate: "https://pressbooks.directory/?search={{query}}",
    sourceType: "oer",
    region: "global",
    country: "international",
    accessDefault: "Free online where network allows",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Network hosts vary; confirm rights on each book’s site.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    futureHarvestMode: "metadata_feed",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "anu_press",
    label: "Australian National University Press",
    description: "ANU open access scholarly books.",
    baseUrl: "https://press.anu.edu.au",
    searchUrlTemplate: "https://press.anu.edu.au/search/node/{{query}}",
    sourceType: "institutional_press",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "caul_oer_collective",
    label: "CAUL OER Collective",
    description: "Council of Australian University Librarians OER discovery hub (handoff).",
    baseUrl: "https://www.caul.edu.au",
    searchUrlTemplate: "https://oercommons.org/hubs/CAUL?q={{query}}",
    sourceType: "australian_open_collection",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Aggregated OER; verify each item’s licence at the host.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "cdu_open_book_publishing",
    label: "Charles Darwin University — Open Book Publishing",
    description: "Northern Institute open access publishing at CDU.",
    baseUrl: "https://www.cdu.edu.au",
    searchUrlTemplate: "https://www.cdu.edu.au/search?query={{query}}",
    sourceType: "australian_open_collection",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Use site search as interim handoff; harvest OAI when available.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "jcu_open_ebooks",
    label: "James Cook University — Open eBooks",
    description: "JCU open educational publishing and discovery.",
    baseUrl: "https://www.jcu.edu.au",
    searchUrlTemplate: "https://www.jcu.edu.au/search/results?query={{query}}",
    sourceType: "australian_open_collection",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Institutional search handoff until a dedicated OAI feed is wired.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "latrobe_ebureau",
    label: "La Trobe eBureau",
    description: "La Trobe University open access publishing support.",
    baseUrl: "https://www.latrobe.edu.au",
    searchUrlTemplate: "https://www.latrobe.edu.au/search?query={{query}}",
    sourceType: "australian_open_collection",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Use institutional discovery as handoff pending dedicated catalogue API.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "open_textbooks_uq",
    label: "Open Textbooks @ UQ",
    description: "University of Queensland open textbook resources.",
    baseUrl: "https://open.uq.edu.au",
    searchUrlTemplate: "https://open.uq.edu.au/?s={{query}}",
    sourceType: "open_textbook",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "qut_ebooks",
    label: "QUT eBooks",
    description: "Queensland University of Technology library eBook discovery.",
    baseUrl: "https://www.qut.edu.au",
    searchUrlTemplate: "https://www.qut.edu.au/search?q={{query}}",
    sourceType: "australian_open_collection",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Library discovery handoff; verify access and licence per record.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "rmit_open_press",
    label: "RMIT Open Press",
    description: "RMIT University Pressbooks network.",
    baseUrl: "https://rmitopenpress.pressbooks.pub",
    searchUrlTemplate: "https://rmitopenpress.pressbooks.pub/catalogue/?search={{query}}",
    sourceType: "institutional_press",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    futureHarvestMode: "oai_pmh",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "sydney_open_library",
    label: "Sydney Open Library",
    description: "University of Sydney open access library collections.",
    baseUrl: "https://library.sydney.edu.au",
    searchUrlTemplate: "https://library.sydney.edu.au/search?query={{query}}",
    sourceType: "australian_open_collection",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Discovery handoff; confirm rights on the resolved catalogue record.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
  {
    id: "unisq_open_text_catalogue",
    label: "UniSQ Open Text catalogue",
    description: "University of Southern Queensland open educational texts.",
    baseUrl: "https://open.unisq.edu.au",
    searchUrlTemplate: "https://open.unisq.edu.au/?s={{query}}",
    sourceType: "open_textbook",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "university_of_adelaide_press",
    label: "University of Adelaide Press",
    description: "Adelaide University open access press.",
    baseUrl: "https://www.adelaide.edu.au/press",
    searchUrlTemplate: "https://www.adelaide.edu.au/press/search?query={{query}}",
    sourceType: "institutional_press",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Confirm reuse terms on each title page.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "uts_epress",
    label: "UTS ePRESS",
    description: "University of Technology Sydney open access publishing platform.",
    baseUrl: "https://epress.lib.uts.edu.au",
    searchUrlTemplate: "https://epress.lib.uts.edu.au/?s={{query}}",
    sourceType: "institutional_press",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Do not assume Creative Commons unless the record explicitly states it.",
    metadataConfidence: "medium",
    integrationMode: "search_handoff",
    futureHarvestMode: "oai_pmh",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: true,
  },
  {
    id: "western_open_textbooks",
    label: "Western Open Textbooks",
    description: "Western Sydney University open textbook initiative.",
    baseUrl: "https://www.westernsydney.edu.au",
    searchUrlTemplate: "https://www.westernsydney.edu.au/search?query={{query}}",
    sourceType: "open_textbook",
    region: "australia",
    country: "Australia",
    accessDefault: "Free online where source provides access",
    rightsDefault: "Check record-level licence",
    rightsCaution: "Institutional search handoff until a dedicated open textbook index is integrated.",
    metadataConfidence: "low",
    integrationMode: "search_handoff",
    requiresApiKey: false,
    enabled: true,
    canLiveSearch: false,
    canHarvest: false,
  },
];

export function getOpenAccessSourceById(id: string): OpenAccessSource | undefined {
  return OPEN_ACCESS_SOURCES.find((s) => s.id === id);
}
