import QualityScan from "@/components/knowledge/QualityScan";
import { createClient } from "@/src/lib/supabase/server";
import Link from "next/link";
import { existsSync } from "node:fs";
import path from "node:path";
import { requireAdmin } from "@/src/lib/auth";
import { loadCatalogueRecords } from "@/lib/catalogue/store";
import { resolveServerRecordImage } from "@/lib/catalogue/record-image-server";
import { auditCatalogue } from "@/lib/knowledge/quality";
export const metadata={title:"Archive quality | ARED Admin"};
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{issue?:string}>}){
 await requireAdmin();const {issue}=await searchParams;const records=loadCatalogueRecords();const images=new Map(records.map(r=>{const image=resolveServerRecordImage(r);const url=image.url;return [r.id,{url,missingLocal:Boolean(url?.startsWith('/images/')&&!existsSync(path.join(process.cwd(),'public',url)))}];}));const db=await createClient();const [{data:health,error:healthError},{data:coverage,error:coverageError}]=await Promise.all([db.from('archive_url_health').select('url,status,checked_at'),db.from('archive_record_exposures').select('record_id')]);const rows=auditCatalogue(records,images,coverageError?undefined:new Set((coverage??[]).map(c=>c.record_id)));for(const r of records){const row=rows.find(x=>x.id===r.id)!;for(const [label,url] of [['External source',r.sourceUrl],['External image',images.get(r.id)?.url]]){const h=health?.find(x=>x.url===url);if(h&&(h.status===null||h.status>=400))row.issues.push(`${label} unreachable at last check`);}}const counts=new Map<string,number>();for(const r of rows)for(const label of r.issues)counts.set(label,(counts.get(label)??0)+1);const shown=rows.filter(r=>issue?r.issues.includes(issue):r.issues.length>0);
 return <div className="admin-dashboard"><h1>Archive quality</h1><p>{records.length.toLocaleString()} catalogue records. Findings are review prompts, not automatic deletions or provenance judgements.</p><p>Images withheld for rights or cultural protocols are included under “No displayable image”; do not bypass those restrictions. External checks record the latest HTTP result, not a permanent verdict. “No recorded discovery exposure” means no observed tile since this tracking began; it does not prove the record has never appeared.</p><QualityScan />{(healthError||coverageError)&&<p role="alert">Some persisted checks could not load.</p>}<div style={{display:'flex',flexWrap:'wrap',gap:12,margin:'28px 0'}}>{[...counts].map(([label,count])=><Link key={label} className="admin-button admin-button-secondary" href={`/admin/archive-quality?issue=${encodeURIComponent(label)}`}>{label} · {count}</Link>)}</div><Link href="/admin/knowledge-proposals">Review knowledge contributions ↗</Link><p>{shown.length} records match. Showing the first 200.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Record</th><th>Review</th></tr></thead><tbody>{shown.slice(0,200).map(r=><tr key={r.id}><td><Link href={`/records/${encodeURIComponent(r.id)}`}>{r.title}</Link><small style={{display:'block'}}>{r.id}</small></td><td>{r.issues.join(' · ')}</td></tr>)}</tbody></table></div></div>;
}
