/**
 * Export ARED master taxonomy and research catalogue CSV files.
 * Run: npx tsx scripts/export-ared-catalogue.ts
 */

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import {
  flattenTaxonomyForExport,
  RESEARCH_CATALOGUE_COLUMNS,
  type ResearchCatalogueRecord,
  type TaxonomyRow,
} from "../lib/data/ared-master-taxonomy";
import {
  mergeResearchCatalogue,
  getResearchCatalogueStats,
} from "../lib/data/ared-research-catalogue-generator";

const OUT_DIR = join(process.cwd(), "data", "catalogue");

function escapeCsv(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function rowsToCsv(headers: readonly string[], rows: Record<string, string | number | null>[]): string {
  const lines = [headers.join(",")];
  for (const row of rows) {
    lines.push(headers.map((h) => escapeCsv(row[h] ?? null)).join(","));
  }
  return lines.join("\n") + "\n";
}

function taxonomyToRows(taxonomy: TaxonomyRow[]): Record<string, string | number | null>[] {
  return taxonomy.map((t) => ({
    scheme: t.scheme,
    slug: t.slug,
    label: t.label,
    broader: t.broader,
    definition: t.definition,
    central_question: t.central_question,
    indicative_period: t.indicative_period,
    target_count: t.target_count,
    catalogue_fields: t.catalogue_fields,
    related_terms: t.related_terms,
  }));
}

/** Seed research rows — priority targets for first catalogue build */
const SEED_RESEARCH_RECORDS: ResearchCatalogueRecord[] = [
  {
    record_id: "rc-001",
    archive_item_id: null,
    title: "Sankofa bird goldweight — figurative proverbial form",
    historical_periods: ["coastal-contact-transcultural", "colonial-print-institutional"],
    region: "akan-central",
    locality: null,
    visual_system: "land-cosmology-authority",
    visual_system_concept: "goldweights",
    object_type: "Goldweight",
    person: null,
    person_role: null,
    date_display: "c. 1700–1900",
    source_institution: "british-museum",
    source_reference: "BM brass weight collections — verify accession",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "museum_metadata",
    verification_level: "museum_confirmed",
    researcher: null,
    research_notes: "Catalogue geometric vs figurative; tie to proverb, weight function, casting workshop, colonial acquisition.",
    community_notes: null,
    colonial_acquisition_note: "Record BM acquisition history separately from Akan use context.",
    collection_field: "goldweights",
    priority: "critical",
  },
  {
    record_id: "rc-002",
    archive_item_id: null,
    title: "Historic Adinkra cloth with heraldic translation — pre-1826 collection",
    historical_periods: ["coastal-contact-transcultural"],
    region: "akan-central",
    locality: null,
    visual_system: "land-cosmology-authority",
    visual_system_concept: "adinkra-system",
    object_type: "Adinkra cloth",
    person: null,
    person_role: "Maker / craftsperson",
    date_display: "before 1826",
    source_institution: "metropolitan-museum",
    source_reference: "Met Adinkra cloth — verify accession and Met scholarship on heraldic translation",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "literature_review",
    verification_level: "museum_confirmed",
    researcher: null,
    research_notes: "Document Akan translation of foreign heraldic forms; record multiple symbol interpretations.",
    community_notes: null,
    colonial_acquisition_note: "Required — Met collecting history.",
    collection_field: "adinkra-system",
    priority: "critical",
  },
  {
    record_id: "rc-003",
    archive_item_id: null,
    title: "Asafo company flag — proverbial imagery, Fante coast",
    historical_periods: ["colonial-print-institutional", "post-independence-popular"],
    region: "akan-central",
    locality: "Central Region",
    visual_system: "memory-proverb-performance",
    visual_system_concept: "asafo-flags",
    object_type: "Asafo flag",
    person: "Kobina Badowah",
    person_role: "Asafo flag maker",
    date_display: "c. mid-20th century",
    source_institution: "fowler-rom",
    source_reference: "Fowler Museum Asafo collection — verify item",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "literature_review",
    verification_level: "provisional",
    researcher: null,
    research_notes: "Document company, town, flag name, proverb, performance use, canton type, art market vs ceremonial distinction.",
    community_notes: "Community authority must govern access to verbal interpretation.",
    colonial_acquisition_note: null,
    collection_field: "asafo-flags",
    priority: "critical",
  },
  {
    record_id: "rc-004",
    archive_item_id: null,
    title: "Asafo flag maker authority record — Kweku Kakanu",
    historical_periods: ["post-independence-popular"],
    region: "akan-central",
    locality: null,
    visual_system: "memory-proverb-performance",
    visual_system_concept: "asafo-flags",
    object_type: "Person authority record",
    person: "Kweku Kakanu",
    person_role: "Asafo flag maker",
    date_display: null,
    source_institution: "fowler-rom",
    source_reference: "Verify through museum catalogues and local oral histories",
    rights_status: "metadata_only",
    ingestion_route: "field_research",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Do not build full authority record until verified via museum catalogues and local oral history.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "asafo-flags",
    priority: "high",
  },
  {
    record_id: "rc-005",
    archive_item_id: "gh-flag-okoh",
    title: "Ghana national flag — design by Theodosia Salome Okoh",
    historical_periods: ["anticolonial-independence"],
    region: "multi-regional",
    locality: "Accra",
    visual_system: "independence-state-visual-identity",
    visual_system_concept: "theodosia-okoh",
    object_type: "Flag / emblem",
    person: "Theodosia Salome Okoh",
    person_role: "Designer",
    date_display: "1957",
    source_institution: "family-archives",
    source_reference: "Family archives, official specifications — gather sketches and interviews",
    rights_status: "permission_required",
    ingestion_route: "field_research",
    research_status: "literature_review",
    verification_level: "provisional",
    researcher: null,
    research_notes: "Full designer authority record: sketches, interviews, reproductions, official specs, later changes.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "independence-state-visual-identity",
    priority: "critical",
  },
  {
    record_id: "rc-006",
    archive_item_id: null,
    title: "Coat of arms of Ghana — Nii Amon Kotei",
    historical_periods: ["anticolonial-independence"],
    region: "multi-regional",
    locality: "Accra",
    visual_system: "independence-state-visual-identity",
    visual_system_concept: "amon-kotei",
    object_type: "Coat of arms / heraldic design",
    person: "Nii Amon Kotei",
    person_role: "Designer",
    date_display: "1957",
    source_institution: "national-archives-ghana",
    source_reference: "Commissioning records — verify",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "not_started",
    verification_level: "provisional",
    researcher: null,
    research_notes: "Preparatory work, heraldic sources, indigenous symbols, institutional use over time.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "independence-state-visual-identity",
    priority: "critical",
  },
  {
    record_id: "rc-007",
    archive_item_id: null,
    title: "Kofi Antubam — Presidential Seat / State Chair commission",
    historical_periods: ["anticolonial-independence", "post-independence-popular"],
    region: "multi-regional",
    locality: null,
    visual_system: "independence-state-visual-identity",
    visual_system_concept: "kofi-antubam",
    object_type: "Regalia / ritual object",
    person: "Kofi Antubam",
    person_role: "Designer",
    date_display: "c. 1960s",
    source_institution: "knust",
    source_reference: "KNUST / Achimota networks — verify",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Treat as state visual culture designer; map furniture, mace, architecture, public commissions.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "independence-state-visual-identity",
    priority: "high",
  },
  {
    record_id: "rc-008",
    archive_item_id: null,
    title: "Daily Graphic — masthead and front page typographic history",
    historical_periods: ["anticolonial-independence", "post-independence-popular", "democratic-digital-diasporic"],
    region: "multi-regional",
    locality: "Accra",
    visual_system: "print-colonial-public-culture",
    visual_system_concept: "newspapers-editorial-cartoons",
    object_type: "Newspaper / periodical",
    person: null,
    person_role: "Publisher",
    date_display: "1950–present",
    source_institution: "graphic-communications-group",
    source_reference: "Daily Graphic archive — corporate permissions required",
    rights_status: "permission_required",
    ingestion_route: "metadata_record",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Gather mastheads, front pages, cartoons, typefaces, ownership, censorship history across decades.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "newspapers-editorial-cartoons",
    priority: "high",
  },
  {
    record_id: "rc-009",
    archive_item_id: null,
    title: "Sirigu women's wall-painting tradition — compound mural",
    historical_periods: ["visual-systems-before-colonial", "democratic-digital-diasporic"],
    region: "kassena",
    locality: "Sirigu",
    visual_system: "land-cosmology-authority",
    visual_system_concept: "architecture-wall-painting-body-graphics",
    object_type: "Architecture / mural",
    person: null,
    person_role: "Maker / craftsperson",
    date_display: null,
    source_institution: "local-artists-workshops",
    source_reference: "Field research — Sirigu community",
    rights_status: "permission_required",
    ingestion_route: "field_research",
    research_status: "field_research_planned",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Northern Ghana strand; geometric mural systems, compound decoration; community consent required.",
    community_notes: "Community authority must govern what is recorded and shown.",
    colonial_acquisition_note: null,
    collection_field: null,
    priority: "high",
  },
  {
    record_id: "rc-010",
    archive_item_id: null,
    title: "Ewe kente — named cloth, distinct weaving tradition",
    historical_periods: ["visual-systems-before-colonial", "coastal-contact-transcultural"],
    region: "ewe",
    locality: "Volta Region",
    visual_system: "cloth-pattern-social-identity",
    visual_system_concept: "ewe-kente",
    object_type: "Kente cloth",
    person: null,
    person_role: "Weaver",
    date_display: null,
    source_institution: "ghana-museums-monuments",
    source_reference: "GMMB textile collections — verify",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Resist presenting kente as one national style; document Ewe structure, naming, patron, occasion.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "cloth-pattern-social-identity",
    priority: "high",
  },
  {
    record_id: "rc-011",
    archive_item_id: null,
    title: "Hand-painted cinema poster — flour sack support",
    historical_periods: ["post-independence-popular"],
    region: "multi-regional",
    locality: "Accra",
    visual_system: "popular-everyday-graphics",
    visual_system_concept: "cinema-posters",
    object_type: "Cinema poster",
    person: null,
    person_role: "Sign writer",
    date_display: "c. 1980s–1990s",
    source_institution: "local-artists-workshops",
    source_reference: "Verify artist, video club, cinema vs tourist sale distinction",
    rights_status: "metadata_only",
    ingestion_route: "field_research",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Catalogue artist, film, location, support, repainting, export history, active cinema use vs tourist sale.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "music-covers",
    priority: "medium",
  },
  {
    record_id: "rc-012",
    archive_item_id: null,
    title: "Colonial postcard — critical metadata model template",
    historical_periods: ["colonial-print-institutional"],
    region: "multi-regional",
    locality: null,
    visual_system: "print-colonial-public-culture",
    visual_system_concept: "colonial-maps-photography",
    object_type: "Photograph / postcard",
    person: null,
    person_role: "Photographer",
    date_display: null,
    source_institution: "national-archives-ghana",
    source_reference: "Template row — replace with specific item",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Preserve colonial caption separately; add Ghanaian curatorial description.",
    community_notes: "Corrective community description required where people are depicted.",
    colonial_acquisition_note: "Required for all colonial photography records.",
    collection_field: "newspapers-editorial-cartoons",
    priority: "medium",
  },
  {
    record_id: "rc-013",
    archive_item_id: null,
    title: "Achimota School art education network — institutional history",
    historical_periods: ["colonial-print-institutional", "anticolonial-independence"],
    region: "multi-regional",
    locality: "Accra",
    visual_system: "independence-state-visual-identity",
    visual_system_concept: "kofi-antubam",
    object_type: "Institutional logo / identity",
    person: null,
    person_role: "Institution",
    date_display: "1920s–present",
    source_institution: "knust",
    source_reference: "Achimota archives, curriculum histories",
    rights_status: "metadata_only",
    ingestion_route: "metadata_record",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Map programme names, lecturers, student work, exhibitions, typography teaching, alumni networks.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: null,
    priority: "medium",
  },
  {
    record_id: "rc-014",
    archive_item_id: null,
    title: "Ga Homowo festival graphics",
    historical_periods: ["visual-systems-before-colonial", "democratic-digital-diasporic"],
    region: "ga-dangme",
    locality: "Accra",
    visual_system: "memory-proverb-performance",
    visual_system_concept: "processions-festivals",
    object_type: "Regalia / ritual object",
    person: null,
    person_role: null,
    date_display: null,
    source_institution: "local-artists-workshops",
    source_reference: "Field research — Ga-Dangme communities",
    rights_status: "permission_required",
    ingestion_route: "field_research",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Ga stools, royal emblems, fishing-boat inscriptions, fantasy coffins, urban signage.",
    community_notes: "Community consent required.",
    colonial_acquisition_note: null,
    collection_field: null,
    priority: "medium",
  },
  {
    record_id: "rc-015",
    archive_item_id: null,
    title: "Adinkra symbol record — multiple interpretations dispute template",
    historical_periods: ["visual-systems-before-colonial"],
    region: "akan-central",
    locality: "Ntonso",
    visual_system: "land-cosmology-authority",
    visual_system_concept: "adinkra-system",
    object_type: "Adinkra symbol record",
    person: null,
    person_role: null,
    date_display: null,
    source_institution: "local-artists-workshops",
    source_reference: "Record disagreements and multiple interpretations — not fixed English meanings",
    rights_status: "metadata_only",
    ingestion_route: "field_research",
    research_status: "not_started",
    verification_level: "unverified",
    researcher: null,
    research_notes: "Major research problem: websites give one fixed English meaning. Archive must record disagreements.",
    community_notes: null,
    colonial_acquisition_note: null,
    collection_field: "adinkra-system",
    priority: "high",
  },
];

function researchRecordToRow(r: ResearchCatalogueRecord): Record<string, string | number | null> {
  return {
    record_id: r.record_id,
    archive_item_id: r.archive_item_id,
    title: r.title,
    historical_periods: r.historical_periods.join("|"),
    region: r.region,
    locality: r.locality,
    visual_system: r.visual_system,
    visual_system_concept: r.visual_system_concept,
    object_type: r.object_type,
    person: r.person,
    person_role: r.person_role,
    date_display: r.date_display,
    source_institution: r.source_institution,
    source_reference: r.source_reference,
    rights_status: r.rights_status,
    ingestion_route: r.ingestion_route,
    research_status: r.research_status,
    verification_level: r.verification_level,
    researcher: r.researcher,
    research_notes: r.research_notes,
    community_notes: r.community_notes,
    colonial_acquisition_note: r.colonial_acquisition_note,
    collection_field: r.collection_field,
    priority: r.priority,
  };
}

const TAXONOMY_HEADERS = [
  "scheme",
  "slug",
  "label",
  "broader",
  "definition",
  "central_question",
  "indicative_period",
  "target_count",
  "catalogue_fields",
  "related_terms",
] as const;

mkdirSync(OUT_DIR, { recursive: true });

const taxonomy = flattenTaxonomyForExport();
writeFileSync(
  join(OUT_DIR, "master-taxonomy.csv"),
  rowsToCsv(TAXONOMY_HEADERS, taxonomyToRows(taxonomy))
);

writeFileSync(
  join(OUT_DIR, "research-catalogue.csv"),
  rowsToCsv(RESEARCH_CATALOGUE_COLUMNS, mergeResearchCatalogue(SEED_RESEARCH_RECORDS).map(researchRecordToRow))
);

const allResearch = mergeResearchCatalogue(SEED_RESEARCH_RECORDS);
const stats = getResearchCatalogueStats(allResearch);

console.log(`Exported ${taxonomy.length} taxonomy rows → data/catalogue/master-taxonomy.csv`);
console.log(`Exported ${allResearch.length} research rows → data/catalogue/research-catalogue.csv`);
console.log(`Research catalogue by field:`, stats.byField);
