// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(admin)/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/backup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/backup">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/backup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/backup/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/backup/pages">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/backup/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/collections">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/invites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invites">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/invites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/pages/bk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages/bk">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/pages/bk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/records">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/settings/bk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/bk">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/settings/bk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sources">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-login">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invite/[token]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/signin">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../../app/(app)/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/community/reading-lists/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community/reading-lists/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/community/reading-lists/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/copyright/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/copyright">> = Specific
  const handler = {} as typeof import("../../../app/(app)/copyright/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/curator/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curator/media">> = Specific
  const handler = {} as typeof import("../../../app/(app)/curator/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/curator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curator">> = Specific
  const handler = {} as typeof import("../../../app/(app)/curator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/bookmarks">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/lists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/lists">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/lists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/searches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/searches">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/searches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/collaborators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/collaborators">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/collaborators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/exports">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/notes">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/projects">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/reading-lists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/reading-lists">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/reading-lists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/saved-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/saved-records">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/saved-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/workbench/tasks">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/(app)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/(app)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../../app/(app)/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/(app)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/takedown/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/takedown">> = Specific
  const handler = {} as typeof import("../../../app/(app)/takedown/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/(app)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../../app/(app)/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/about/bk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/bk">> = Specific
  const handler = {} as typeof import("../../../app/about/bk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../../app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../../app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/records/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/records/[id]">> = Specific
  const handler = {} as typeof import("../../../app/records/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sources">> = Specific
  const handler = {} as typeof import("../../../app/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/admin-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-login">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/admin-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/collections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collections">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/collections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/curator/media-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curator/media-links">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/curator/media-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/curator/media/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curator/media/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/curator/media/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/curator/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curator/media">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/curator/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/external-open-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external-open-access">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/external-open-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/reading-lists/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-lists/[id]/export">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/reading-lists/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/reading-lists/export-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-lists/export-all">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/reading-lists/export-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/records">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/site-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-content">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/site-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sources">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/workbench/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workbench/export">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/workbench/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api/workspace/record-tools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/record-tools">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api/workspace/record-tools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/confirm">> = Specific
  const handler = {} as typeof import("../../../app/auth/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/signout">> = Specific
  const handler = {} as typeof import("../../../app/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(admin)/admin/backup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/backup">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/backup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/my/workbench/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/my/workbench">> = Specific
  const handler = {} as typeof import("../../../app/(app)/my/workbench/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
